import { useMemo, useState } from "react";
import { defaultRecapPrompt, type AppSettings, type RecapSectionKey } from "@minutesbot/shared";

type RecapSettings = AppSettings["recap"];
export type RecapTemplateId = "auto" | "weekly_spqrc" | "weekly_sales" | "plant_meeting" | "general";

type RecapTemplate = {
  id: RecapTemplateId;
  title: string;
  description: string;
  badge?: string;
  structure: string[];
  prompt: string;
};

type TemplatePreview = {
  meetingNoteHeadings: string[];
  followUpTaskTitles: string[];
  sampleHeading: string;
  sampleTitle: string;
  sampleDetail: string;
  sampleTaskTitle: string;
  sampleTaskDetail: string;
  sampleOwners: string;
};

type PreviewMode = "standard" | "brief";

const autoPromptPreview = [
  "Classifier prompt: review the Teams meeting title and full transcript, classify each chunk when needed, and reduce to one final meeting type.",
  "Generator prompt: use the resolved meeting type, do not reclassify, return strict JSON only, do not invent facts, clean up unclear speaker labels, and apply the selected WGS / MinutesBot section order."
].join("\n\n");

export const recapTemplates: RecapTemplate[] = [
  {
    id: "auto",
    title: "Auto-classified WGS recap",
    badge: "ACTIVE DEFAULT",
    description: "Automatically selects the best recap format from the Teams title and full transcript.",
    structure: ["Generated by AI disclaimer", "Meeting metadata", "Weekly summary", "Topic sections", "Decisions", "Action items", "Risks and Blockers", "Open Questions"],
    prompt: autoPromptPreview
  },
  {
    id: "weekly_spqrc",
    title: "Weekly SPQRC",
    description: "SPQRC execution recap with executive summary, plant updates, decisions, risks, and actions.",
    structure: [
      "Meeting type: Weekly SPQRC",
      "Executive Summary",
      "Safety, People, Quality, Delivery, and Cost updates",
      "Plant operations reports",
      "Customer or sales updates",
      "Decisions",
      "Follow-up tasks",
      "Risks and Blockers",
      "Open Questions"
    ],
    prompt: "Use the Weekly SPQRC structure: executive summary, safety/people/quality/delivery/cost updates, plant operations, customer or sales updates, decisions, follow-up tasks, risks and blockers, and open questions."
  },
  {
    id: "weekly_sales",
    title: "Weekly Sales",
    description: "Numbered weekly sales recap with summary, customer follow-up, operations, forecast, CRM, pricing, actions, and risks.",
    structure: [
      "Meeting type: Weekly Sales",
      "Meeting, date, and weekly focus",
      "1. Weekly Summary",
      "2. Key Wins and Progress",
      "3. Sales Pipeline and Customer Follow-Up",
      "4. Staffing and Operations",
      "5. Revenue, Forecast, and Reporting",
      "6. CRM and Tracking",
      "7. Pricing and Contract Discussion",
      "8. Decisions Made",
      "9. Action Items",
      "10. Risks and Blockers",
      "11. Open Questions"
    ],
    prompt: "Use the Weekly Sales structure: meeting/date/weekly focus, 1. Weekly Summary, 2. Key Wins and Progress, 3. Sales Pipeline and Customer Follow-Up, 4. Staffing and Operations, 5. Revenue Forecast and Reporting, 6. CRM and Tracking, 7. Pricing and Contract Discussion, 8. Decisions Made, 9. Action Items, 10. Risks and Blockers, and 11. Open Questions. Clean up unclear speaker labels such as Conference Room Computer."
  },
  {
    id: "plant_meeting",
    title: "Individual Plant Meeting",
    description: "Plant recap with operations, schedule, safety, quality, staffing, constraints, risks, and actions.",
    structure: [
      "Meeting type: Individual Plant Meeting",
      "Executive Summary",
      "Plant operations and safety reports",
      "Production, schedule, and customer updates",
      "Quality and customer issues",
      "Maintenance, equipment, and material constraints",
      "Staffing and operational updates",
      "Decisions",
      "Follow-up tasks",
      "Risks and Blockers",
      "Open Questions"
    ],
    prompt: "Use the Individual Plant Meeting structure: executive summary, plant operations and safety, production/schedule/customer updates, quality and customer issues, maintenance/equipment/material constraints, staffing and operational updates, decisions, follow-up tasks, risks and blockers, and open questions."
  },
  {
    id: "general",
    title: "General",
    description: "Default recap for meetings that do not match SPQRC, sales, or plant templates.",
    structure: [
      "Meeting type: General",
      "Executive Summary",
      "Key discussion topics",
      "Project or business updates",
      "Operational updates",
      "Customer or stakeholder updates",
      "Decisions",
      "Follow-up tasks",
      "Risks and Blockers",
      "Open Questions"
    ],
    prompt: "Use the General structure: executive summary, key discussion topics, project or business updates, operational updates, customer or stakeholder updates, decisions, follow-up tasks, risks and blockers, and open questions."
  }
];

const classificationLogic = [
  ["Weekly SPQRC", "Safety, People, Quality, Responsiveness/Delivery, and Cost review."],
  ["Weekly Sales", "Pipeline, forecast, customers, quotes, wins/losses, and revenue risks."],
  ["Individual Plant Meeting", "Plant/site operations, production, safety, quality, maintenance, and materials."],
  ["General", "Fallback recap for all other meeting types."]
] as const;

const templatePreviews: Record<RecapTemplateId, TemplatePreview> = {
  auto: {
    meetingNoteHeadings: ["Executive Summary", "Program and Compliance Updates", "Risks and Blockers", "Open Questions"],
    followUpTaskTitles: ["Assigned Next Steps"],
    sampleHeading: "Executive Summary:",
    sampleTitle: "Meeting Focus:",
    sampleDetail: "The recap will summarize the meeting focus, key progress, major risks, and ownership gaps before grouping the detailed topic notes.",
    sampleTaskTitle: "Assigned Next Steps:",
    sampleTaskDetail: "The recap will list concrete follow-up tasks with owners, due dates, and expected outcomes when stated.",
    sampleOwners: "assigned owners"
  },
  weekly_spqrc: {
    meetingNoteHeadings: ["Executive Summary", "Safety, People, Quality, Delivery, and Cost Updates", "Plant Operations Reports", "Decisions", "Risks and Blockers"],
    followUpTaskTitles: ["Corrective actions", "Plant manager follow-ups", "KPI data validation", "Next review preparation"],
    sampleHeading: "Safety, People, Quality, Delivery, and Cost Updates:",
    sampleTitle: "Execution Focus:",
    sampleDetail: "The recap will preserve stated SPQRC metrics, plant impacts, owners, corrective actions, and next review priorities.",
    sampleTaskTitle: "Corrective Actions:",
    sampleTaskDetail: "Complete assigned safety, quality, delivery, or cost follow-ups before the next SPQRC review.",
    sampleOwners: "plant managers"
  },
  weekly_sales: {
    meetingNoteHeadings: ["1. Weekly Summary", "2. Key Wins and Progress", "3. Sales Pipeline and Customer Follow-Up", "4. Staffing and Operations", "5. Revenue, Forecast, and Reporting", "6. CRM and Tracking", "7. Pricing and Contract Discussion", "8. Decisions Made", "9. Action Items", "10. Risks and Blockers", "11. Open Questions"],
    followUpTaskTitles: ["Customer follow-ups", "Quote preparation", "CRM updates", "Forecast cleanup", "Staffing actions"],
    sampleHeading: "1. Weekly Summary:",
    sampleTitle: "Weekly Focus:",
    sampleDetail: "The recap will summarize current sales activity, customer follow-ups, active trial work, staffing needs, forecast cleanup, CRM transition, schedule risks, and the stated weekly focus.",
    sampleTaskTitle: "9. Action Items:",
    sampleTaskDetail: "List each concrete follow-up with owner and due timing, including customer emails, quote work, CRM migration, staffing clarification, and reporting cleanup when stated.",
    sampleOwners: "sales owners"
  },
  plant_meeting: {
    meetingNoteHeadings: ["Executive Summary", "Plant Operations and Safety Reports", "Production, Schedule, and Customer Updates", "Quality and Customer Issues", "Maintenance, Equipment, and Material Constraints", "Staffing and Operational Updates"],
    followUpTaskTitles: ["Production actions", "Maintenance follow-ups", "Staffing actions", "Quality issue closure"],
    sampleHeading: "Plant Operations and Safety Reports:",
    sampleTitle: "Operating Status:",
    sampleDetail: "The recap will capture plant-specific safety, production, schedule, quality, staffing, maintenance, material, delivery, and customer-impact details.",
    sampleTaskTitle: "Maintenance Follow-Ups:",
    sampleTaskDetail: "Complete production, maintenance, staffing, or quality issue follow-ups with plant owners and due dates when stated.",
    sampleOwners: "plant team"
  },
  general: {
    meetingNoteHeadings: ["Executive Summary", "Key Discussion Topics", "Project or Business Updates", "Decisions", "Risks and Blockers", "Open Questions"],
    followUpTaskTitles: ["Assigned next steps", "Pending decisions", "Follow-up meetings"],
    sampleHeading: "Executive Summary:",
    sampleTitle: "Meeting Focus:",
    sampleDetail: "The recap will summarize the main discussion, outcomes, risks, and unresolved questions before grouping the detailed topic notes.",
    sampleTaskTitle: "Assigned Next Steps:",
    sampleTaskDetail: "Complete assigned next steps, pending decisions, or follow-up meetings with owners and due dates when stated.",
    sampleOwners: "assigned owners"
  }
};

export function RecapForm({
  value,
  onChange,
  onSave,
  saving = false
}: {
  value: RecapSettings;
  onChange: (recap: RecapSettings) => void;
  onSave?: () => void | Promise<void>;
  saving?: boolean;
}) {
  const [selectedTemplateId, setSelectedTemplateId] = useState<RecapTemplateId>("auto");
  const [libraryTab, setLibraryTab] = useState<"suggested" | "custom">("suggested");
  const [previewMode, setPreviewMode] = useState<PreviewMode>("standard");
  const [copyMessage, setCopyMessage] = useState("");
  const selectedTemplate = useMemo(() => getTemplateById(selectedTemplateId), [selectedTemplateId]);
  const selectedPreview = useMemo(() => getTemplatePreview(selectedTemplateId), [selectedTemplateId]);
  const update = <K extends keyof RecapSettings>(key: K, next: RecapSettings[K]) => onChange({ ...value, [key]: next });
  const promptPreview = getPromptPreview(selectedTemplate.id, value.prompt);

  return (
    <form className="recapTemplatePage">
      <section className="recapSettingsStrip" aria-label="Recap settings">
        <Field label="Whisper model" value={value.transcriptionModel} onChange={(next) => update("transcriptionModel", next)} />
        <Field label="Language" value={value.language ?? ""} placeholder="Auto-detect" onChange={(next) => update("language", next)} />
        <Field label="Subject prefix" value={value.subjectPrefix} onChange={(next) => update("subjectPrefix", next)} />
        <TextAreaField label="Intro text" value={value.introText ?? ""} rows={2} onChange={(next) => update("introText", next)} />
      </section>

      <div className="recapTemplateGrid">
        <aside className="recapCard templateLibrary">
          <div className="sectionHeader">
            <h2>Templates</h2>
          </div>
          <div className="segmentedControl" role="tablist" aria-label="Template library">
            <button type="button" className={libraryTab === "suggested" ? "active" : ""} onClick={() => setLibraryTab("suggested")}>
              Suggested
            </button>
            <button type="button" className={libraryTab === "custom" ? "active" : ""} onClick={() => setLibraryTab("custom")}>
              Custom
            </button>
          </div>
          {libraryTab === "suggested" ? (
            <div className="templateList">
              {recapTemplates.map((template) => (
                <button
                  type="button"
                  key={template.id}
                  className={`templateListItem ${selectedTemplateId === template.id ? "active" : ""}`}
                  onClick={() => setSelectedTemplateId(template.id)}
                >
                  <span>{template.title}</span>
                  <small>{template.description}</small>
                </button>
              ))}
            </div>
          ) : (
            <p className="mutedText">Custom templates are not available yet.</p>
          )}
        </aside>

        <section className="recapCard templatePreview">
          <div className="previewHeader">
            <div>
              <h2>{selectedTemplate.title}</h2>
              <p>{selectedTemplate.id === "auto" ? "Automatically reviews the Teams meeting title and full transcript, classifies the meeting, and applies the best recap structure." : selectedTemplate.description}</p>
            </div>
            {selectedTemplate.badge && <span className="badge good">{selectedTemplate.badge}</span>}
          </div>

          {selectedTemplate.id === "auto" && (
            <section className="previewSection">
              <h3>Classification logic</h3>
              <div className="classificationGrid">
                {classificationLogic.map(([title, description]) => (
                  <div className="logicCard" key={title}>
                    <strong>{title}</strong>
                    <span>{description}</span>
                  </div>
                ))}
              </div>
            </section>
          )}

          <section className="previewSection">
            <h3>Notes structure preview</h3>
            <div className="segmentedControl previewModeControl" role="tablist" aria-label="Preview mode">
              <button type="button" className={previewMode === "standard" ? "active" : ""} onClick={() => setPreviewMode("standard")}>
                Standard
              </button>
              <button type="button" className={previewMode === "brief" ? "active" : ""} onClick={() => setPreviewMode("brief")}>
                Brief meeting
              </button>
            </div>
            <div className="teamsPreview">
              {previewMode === "standard" ? <StandardPreview selectedPreview={selectedPreview} /> : <BriefPreview />}
            </div>
          </section>

          <section className="previewSection">
            <h3>Prompt preview</h3>
            <textarea className="promptPreview" readOnly rows={10} value={promptPreview} />
          </section>

          <div className="actions">
            <button type="button" className="secondaryButton" onClick={() => update("prompt", defaultRecapPrompt)}>
              Reset to WGS default
            </button>
            <button
              type="button"
              className="secondaryButton"
              onClick={async () => setCopyMessage(await copyPromptText(promptPreview, typeof navigator === "undefined" ? undefined : navigator.clipboard))}
            >
              Copy prompt
            </button>
            <button type="button" disabled={saving} onClick={onSave}>
              {saving ? "Saving..." : "Save recap"}
            </button>
            {copyMessage && <span className="fieldHelp">{copyMessage}</span>}
          </div>
        </section>

        <aside className="recapCard automationPanel">
          <h2>Automation</h2>
          <dl className="automationFacts">
            <div>
              <dt>Status</dt>
              <dd>{value.classificationEnabled ? "Automatic classification enabled" : "Automatic classification disabled"}</dd>
            </div>
            <div>
              <dt>Classifier input</dt>
              <dd>Teams title + full transcript</dd>
            </div>
            <div>
              <dt>Default behavior</dt>
              <dd>Apply to all meetings</dd>
            </div>
          </dl>

          <label className="check compactCheck automationToggle">
            <input type="checkbox" checked={value.classificationEnabled} onChange={(event) => update("classificationEnabled", event.target.checked)} />
            <span>Automatic classification enabled</span>
          </label>

          <section className="previewSection">
            <h3>Meeting types</h3>
            <ul className="compactList">
              <li>Weekly SPQRC</li>
              <li>Weekly Sales</li>
              <li>Individual Plant Meeting</li>
              <li>General fallback</li>
            </ul>
          </section>

          <section className="previewSection">
            <h3>Short meeting handling</h3>
            <p className="aiDisclaimer">Automatic brief recap enabled</p>
            <ul className="compactList">
              <li>Calendar or transcript duration is {value.shortMeetingDurationThresholdMinutes ?? 2} minutes or less</li>
              <li>Transcript has very little substantive discussion</li>
              <li>No full template is generated for short meetings</li>
              <li>Clear decisions and tasks are still captured</li>
            </ul>
          </section>

          <section className="previewSection">
            <h3>Recap email layout</h3>
            <div className="layoutChecks">
              {value.sections.map((section) => (
                <label className="check compactCheck" key={section.key}>
                  <input
                    type="checkbox"
                    checked={section.enabled}
                    onChange={(event) => update("sections", updateSection(value.sections, section.key, { enabled: event.target.checked }))}
                  />
                  <span>{sectionLabel(section.key)}</span>
                </label>
              ))}
            </div>
          </section>

          <section className="previewSection">
            <h3>Generation rules</h3>
            <ul className="compactList">
              <li>Strict JSON only</li>
              <li>No invented facts</li>
              <li>Owners and due dates captured when stated</li>
              <li>Missing details marked as Not specified, Unclear, or TBD</li>
            </ul>
          </section>

          <button type="button" disabled={saving} onClick={onSave}>
            {saving ? "Saving..." : "Save recap"}
          </button>
        </aside>
      </div>
    </form>
  );
}

function StandardPreview({ selectedPreview }: { selectedPreview: TemplatePreview }) {
  return (
    <>
      <p className="aiDisclaimer">Generated by AI. Be sure to check for accuracy.</p>
      <h4>Meeting notes</h4>
      <div className="teamsPreviewBlock teamsNoteBlock">
        <strong>{selectedPreview.sampleHeading}</strong>
        <p><b>{selectedPreview.sampleTitle}</b></p>
        <p>{selectedPreview.sampleDetail}</p>
      </div>
      <div className="structureList">
        {selectedPreview.meetingNoteHeadings.map((item) => (
          <span key={item}>{item}</span>
        ))}
      </div>
      <h4>Follow-up tasks</h4>
      <div className="teamsPreviewBlock teamsTaskBlock">
        <strong>{selectedPreview.sampleTaskTitle}</strong>
        <p>{selectedPreview.sampleTaskDetail} ({selectedPreview.sampleOwners})</p>
      </div>
      <div className="structureList">
        {selectedPreview.followUpTaskTitles.map((item) => (
          <span key={item}>{item}</span>
        ))}
      </div>
    </>
  );
}

function BriefPreview() {
  return (
    <>
      <p className="aiDisclaimer">Generated by AI. Be sure to check for accuracy.</p>
      <p className="briefPreviewCallout">Brief meeting detected</p>
      <h4>Meeting notes</h4>
      <div className="teamsPreviewBlock teamsNoteBlock">
        <strong>Brief meeting recap:</strong>
        <p><b>What happened:</b></p>
        <p>The recap will summarize only the limited substantive content captured in a very short meeting.</p>
        <p><b>Outcome:</b></p>
        <p>The recap will identify any clear decision or state that no substantive outcome was captured.</p>
      </div>
      <h4>Follow-up tasks</h4>
      <div className="teamsPreviewBlock teamsTaskBlock">
        <p>Only clearly stated follow-up tasks will appear.</p>
      </div>
    </>
  );
}

export function getTemplateById(id: RecapTemplateId): RecapTemplate {
  return recapTemplates.find((template) => template.id === id) ?? recapTemplates[0];
}

export function getTemplatePreview(id: RecapTemplateId): TemplatePreview {
  return templatePreviews[id] ?? templatePreviews.auto;
}

export function getPromptPreview(templateId: RecapTemplateId, savedPrompt: string): string {
  const template = getTemplateById(templateId);
  if (templateId === "auto") return `${template.prompt}\n\nCurrent saved prompt:\n${savedPrompt}`;
  return `${template.prompt}\n\nCurrent saved prompt:\n${savedPrompt}`;
}

export async function copyPromptText(
  prompt: string,
  clipboard?: Pick<Clipboard, "writeText">
): Promise<"Prompt copied" | "Clipboard unavailable"> {
  if (!clipboard?.writeText) return "Clipboard unavailable";
  await clipboard.writeText(prompt);
  return "Prompt copied";
}

export function updateSection(
  sections: RecapSettings["sections"],
  key: RecapSectionKey,
  patch: Partial<RecapSettings["sections"][number]>
): RecapSettings["sections"] {
  return sections.map((section) => (section.key === key ? { ...section, ...patch } : section));
}

export function moveSection(sections: RecapSettings["sections"], index: number, delta: -1 | 1): RecapSettings["sections"] {
  const nextIndex = index + delta;
  if (nextIndex < 0 || nextIndex >= sections.length) return sections;
  const copy = [...sections];
  const [item] = copy.splice(index, 1);
  copy.splice(nextIndex, 0, item);
  return copy;
}

function sectionLabel(key: RecapSectionKey): string {
  return {
    summary: "Summary",
    decisions: "Decisions",
    actionItems: "Action items",
    openQuestions: "Open questions",
    risks: "Risks",
    followUps: "Follow-ups"
  }[key];
}

function Field({
  label,
  placeholder,
  value,
  onChange
}: {
  label: string;
  placeholder?: string;
  value: string;
  onChange: (value: string) => void;
}) {
  return (
    <label>
      <span>{label}</span>
      <input placeholder={placeholder} value={value} onChange={(event) => onChange(event.target.value)} />
    </label>
  );
}

function TextAreaField({
  label,
  rows,
  value,
  onChange
}: {
  label: string;
  rows: number;
  value: string;
  onChange: (value: string) => void;
}) {
  return (
    <label>
      <span>{label}</span>
      <textarea rows={rows} value={value} onChange={(event) => onChange(event.target.value)} />
    </label>
  );
}
