import { describe, expect, it } from "vitest";
import { defaultSettings } from "@minutesbot/shared";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import {
  RecapForm,
  copyPromptText,
  getPromptPreview,
  getTemplateById,
  getTemplatePreview,
  moveSection,
  recapTemplates,
  updateSection
} from "./RecapForm";

describe("recap form helpers", () => {
  it("updates section labels without mutating the original array", () => {
    const sections = defaultSettings.recap.sections;
    const next = updateSection(sections, "summary", { label: "Overview", enabled: false });

    expect(next.find((section) => section.key === "summary")).toMatchObject({ label: "Overview", enabled: false });
    expect(sections.find((section) => section.key === "summary")).toMatchObject({ label: "Summary", enabled: true });
  });

  it("moves sections by one slot and ignores out-of-range moves", () => {
    const moved = moveSection(defaultSettings.recap.sections, 1, -1);

    expect(moved.map((section) => section.key).slice(0, 2)).toEqual(["decisions", "summary"]);
    expect(moveSection(defaultSettings.recap.sections, 0, -1)).toBe(defaultSettings.recap.sections);
  });

  it("defines one universal recap template", () => {
    expect(recapTemplates.map((template) => template.title)).toEqual(["Universal WGS recap"]);
    expect(getTemplateById("universal").title).toBe("Universal WGS recap");
    expect(getTemplatePreview("universal").meetingNoteHeadings).toContain("1. At a Glance");
    expect(getTemplatePreview("universal").meetingNoteHeadings).toContain("3. Full Action Register");
    expect(getPromptPreview("universal", defaultSettings.recap.prompt)).toContain("Current saved prompt");
  });

  it("renders the universal recap template management surface", () => {
    const html = renderToStaticMarkup(React.createElement(RecapForm, { value: defaultSettings.recap, onChange: () => undefined }));

    expect(html).toContain("Universal template");
    expect(html).toContain("Universal WGS recap");
    expect(html).not.toContain("Auto-classified WGS recap");
    expect(html).not.toContain("Weekly SPQRC");
    expect(html).not.toContain("Weekly Sales");
    expect(html).not.toContain("Individual Plant Meeting");
    expect(html).not.toContain("General fallback");
    expect(html).toContain("Automation");
    expect(html).toContain("Single template applied to all meetings");
    expect(html).not.toContain("Automatic classification enabled");
    expect(html).toContain("Generated by AI. Be sure to check for accuracy.");
    expect(html).toContain("Preview mode");
    expect(html).toContain("Brief meeting");
    expect(html).toContain("Meeting notes");
    expect(html).toContain("Follow-up tasks");
    expect(html).toContain("Short meeting handling");
    expect(html).toContain("Automatic brief recap enabled");
    expect(html).toContain("No long recap is generated for short meetings");
    expect(html).toContain("Prompt preview");
    expect(html).toContain("Copy prompt");
    expect(html).toContain("Save recap");
    expect(html).not.toContain("Whisper model");
    expect(html).not.toContain("Transcription model");
  });

  it("returns teams-style preview headings for the universal template", () => {
    expect(getTemplatePreview("universal").meetingNoteHeadings).toContain("Major Risks / Blockers");
    expect(getTemplatePreview("universal").meetingNoteHeadings).toContain("4. Open Questions");
    expect(getTemplatePreview("universal").meetingNoteHeadings).toContain("5. Reference Notes");
  });

  it("copies prompt text when clipboard is available", async () => {
    const writes: string[] = [];
    const clipboard = {
      async writeText(value: string) {
        writes.push(value);
      }
    };

    await expect(copyPromptText("prompt text", clipboard)).resolves.toBe("Prompt copied");
    expect(writes).toEqual(["prompt text"]);
  });
});
