import { useMemo, useState } from "react";
import { defaultRecapPrompt, type AppSettings, type RecapSectionKey } from "@minutesbot/shared";

type RecapSettings = AppSettings["recap"];
export type RecapTemplateId = "auto" | "weekly_spqrc" | "weekly_sales" | "plant_meeting" | "general";

type RecapTemplate = {
  id: RecapTemplateId;
  title: string;
  description: string;
  badge?: string;
  structure: string[];
  prompt: string;
};

type TemplatePreview = {
  meetingNoteHeadings: string[];
  followUpTaskTitles: string[];
  sampleHeading: string;
  sampleTitle: string;
  sampleDetail: string;
  sampleTaskTitle: string;
  sampleTaskDetail: string;
  sampleOwners: string;
};

type PreviewMode = "standard" | "brief";

const autoPromptPreview = [
  "Classifier prompt: review the Teams meeting title and full transcript, classify each chunk when needed, and reduce to one final meeting type.",
  "Generator prompt: use the resolved meeting type, do not reclassify, return strict JSON only, do not invent facts, and apply the selected recap structure."
].join("\n\n");

export const recapTemplates: RecapTemplate[] = [
  {
    id: "auto",
    title: "Auto-classified recap",
    badge: "ACTIVE DEFAULT",
    description: "Automatically selects the best recap format from the Teams title and full transcript.",
    structure: ["Generated by AI disclaimer", "Meeting notes", "Topic headings", "Subtopic paragraphs", "Follow-up tasks", "Owners and due dates"],
    prompt: autoPromptPreview
  },
  {
    id: "weekly_spqrc",
    title: "Weekly SPQRC",
    description: "Safety, People, Quality, Responsiveness/Delivery, Cost, decisions, risks, and actions.",
    structure: [
      "Meeting type: Weekly SPQRC",
      "Safety",
      "People",
      "Quality",
      "Responsiveness/Delivery",
      "Cost",
      "Top priorities before next meeting",
      "Decisions",
      "Action items",
      "Open questions",
      "Risks",
      "Follow-ups"
    ],
    prompt: "Use the Weekly SPQRC structure: Safety, People, Quality, Responsiveness/Delivery, Cost, top priorities, decisions, action items, open questions, risks, and follow-ups."
  },
  {
    id: "weekly_sales",
    title: "Weekly Sales",
    description: "Pipeline, forecast, customers, quotes, wins/losses, revenue risks, and actions.",
    structure: [
      "Meeting type: Weekly Sales",
      "Sales forecast/pipeline",
      "Customer/account updates",
      "Quotes/pricing",
      "Wins/losses",
      "Risks to revenue",
      "Top priorities before next meeting",
      "Decisions",
      "Action items",
      "Open questions",
      "Risks",
      "Follow-ups"
    ],
    prompt: "Use the Weekly Sales structure: sales forecast/pipeline, customer/account updates, quotes/pricing, wins/losses, revenue risks, top priorities, decisions, action items, open questions, risks, and follow-ups."
  },
  {
    id: "plant_meeting",
    title: "Individual Plant Meeting",
    description: "Plant/site operations, production, safety, quality, maintenance, materials, and actions.",
    structure: [
      "Meeting type: Individual Plant Meeting",
      "Plant/site",
      "Operating status",
      "Safety/people",
      "Production/schedule",
      "Quality/customer issues",
      "Maintenance/materials",
      "Top priorities before next meeting",
      "Decisions",
      "Action items",
      "Open questions",
      "Risks",
      "Follow-ups"
    ],
    prompt: "Use the Individual Plant Meeting structure: plant/site, operating status, safety/people, production/schedule, quality/customer issues, maintenance/materials, top priorities, decisions, action items, open questions, risks, and follow-ups."
  },
  {
    id: "general",
    title: "General",
    description: "Default recap for meetings that do not match SPQRC, sales, or plant templates.",
    structure: [
      "Meeting type: General",
      "Purpose",
      "Key discussion",
      "Current status",
      "Key outcomes",
      "Top priorities before next meeting",
      "Decisions",
      "Action items",
      "Open questions",
      "Risks",
      "Follow-ups"
    ],
    prompt: "Use the General structure: purpose, key discussion, current status, key outcomes, top priorities, decisions, action items, open questions, risks, and follow-ups."
  }
];

const classificationLogic = [
  ["Weekly SPQRC", "Safety, People, Quality, Responsiveness/Delivery, and Cost review."],
  ["Weekly Sales", "Pipeline, forecast, customers, quotes, wins/losses, and revenue risks."],
  ["Individual Plant Meeting", "Plant/site operations, production, safety, quality, maintenance, and materials."],
  ["General", "Fallback recap for all other meeting types."]
] as const;

const templatePreviews: Record<RecapTemplateId, TemplatePreview> = {
  auto: {
    meetingNoteHeadings: ["Program and Compliance Updates", "Plant Operations and Safety Reports"],
    followUpTaskTitles: ["Assigned Next Steps"],
    sampleHeading: "Program and Compliance Updates:",
    sampleTitle: "Annual Requirements:",
    sampleDetail: "The recap will identify major compliance, safety, operational, sales, or plant topics and summarize each with speaker-aware detail.",
    sampleTaskTitle: "Assigned Next Steps:",
    sampleTaskDetail: "The recap will list concrete follow-up tasks with owners, due dates, and expected outcomes when stated.",
    sampleOwners: "assigned owners"
  },
  weekly_spqrc: {
    meetingNoteHeadings: ["Safety Updates", "People and Staffing Updates", "Quality Updates", "Responsiveness and Delivery Updates", "Cost and Productivity Updates"],
    followUpTaskTitles: ["Corrective actions", "Plant manager follow-ups", "KPI data validation", "Next review preparation"],
    sampleHeading: "Safety Updates:",
    sampleTitle: "Corrective Actions:",
    sampleDetail: "The recap will preserve specific safety incidents, corrective actions, owners, plant impacts, and next review priorities when discussed.",
    sampleTaskTitle: "Corrective Actions:",
    sampleTaskDetail: "Complete assigned safety, quality, delivery, or cost follow-ups before the next SPQRC review.",
    sampleOwners: "plant managers"
  },
  weekly_sales: {
    meetingNoteHeadings: ["Sales Pipeline and Forecast Updates", "Customer and Account Engagement Updates", "Quotes and Pricing Updates", "Wins, Losses, and Opportunity Movement", "Revenue Risks and Blockers"],
    followUpTaskTitles: ["Customer follow-ups", "Quote preparation", "CRM updates", "Forecast validation"],
    sampleHeading: "Sales Pipeline and Forecast Updates:",
    sampleTitle: "Pipeline Movement:",
    sampleDetail: "The recap will group pipeline, forecast, quote, customer, and revenue updates into detailed topic notes with named customers and owners when stated.",
    sampleTaskTitle: "Customer Follow-Ups:",
    sampleTaskDetail: "Complete customer follow-ups, quote preparation, CRM updates, and forecast validation with stated owners and timeframes.",
    sampleOwners: "sales owners"
  },
  plant_meeting: {
    meetingNoteHeadings: ["Plant Operations and Safety Reports", "Production and Schedule Updates", "Quality and Customer Issues", "Maintenance, Equipment, and Materials", "Staffing and Attendance Updates"],
    followUpTaskTitles: ["Production actions", "Maintenance follow-ups", "Staffing actions", "Quality issue closure"],
    sampleHeading: "Plant Operations and Safety Reports:",
    sampleTitle: "Plant Updates:",
    sampleDetail: "The recap will capture plant-specific safety, production, quality, staffing, maintenance, material, and delivery details by topic or location.",
    sampleTaskTitle: "Maintenance Follow-Ups:",
    sampleTaskDetail: "Complete production, maintenance, staffing, or quality issue follow-ups with plant owners and due dates when stated.",
    sampleOwners: "plant team"
  },
  general: {
    meetingNoteHeadings: ["Key Discussion Topics", "Project or Business Updates", "Decisions and Announcements", "Risks and Open Issues"],
    followUpTaskTitles: ["Assigned next steps", "Pending decisions", "Follow-up meetings"],
    sampleHeading: "Key Discussion Topics:",
    sampleTitle: "Discussion Update:",
    sampleDetail: "The recap will group the most important business, project, customer, operational, decision, and risk topics into readable Teams-style notes.",
    sampleTaskTitle: "Assigned Next Steps:",
    sampleTaskDetail: "Complete assigned next steps, pending decisions, or follow-up meetings with owners and due dates when stated.",
    sampleOwners: "assigned owners"
  }
};

export function RecapForm({
  value,
  onChange,
  onSave,
  saving = false
}: {
  value: RecapSettings;
  onChange: (recap: RecapSettings) => void;
  onSave?: () => void | Promise<void>;
  saving?: boolean;
}) {
  const [selectedTemplateId, setSelectedTemplateId] = useState<RecapTemplateId>("auto");
  const [libraryTab, setLibraryTab] = useState<"suggested" | "custom">("suggested");
  const [previewMode, setPreviewMode] = useState<PreviewMode>("standard");
  const [copyMessage, setCopyMessage] = useState("");
  const selectedTemplate = useMemo(() => getTemplateById(selectedTemplateId), [selectedTemplateId]);
  const selectedPreview = useMemo(() => getTemplatePreview(selectedTemplateId), [selectedTemplateId]);
  const update = <K extends keyof RecapSettings>(key: K, next: RecapSettings[K]) => onChange({ ...value, [key]: next });
  const promptPreview = getPromptPreview(selectedTemplate.id, value.prompt);

  return (
    <form className="recapTemplatePage">
      <section className="recapSettingsStrip" aria-label="Recap settings">
        <Field label="Whisper model" value={value.transcriptionModel} onChange={(next) => update("transcriptionModel", next)} />
        <Field label="Language" value={value.language ?? ""} placeholder="Auto-detect" onChange={(next) => update("language", next)} />
        <Field label="Subject prefix" value={value.subjectPrefix} onChange={(next) => update("subjectPrefix", next)} />
        <TextAreaField label="Intro text" value={value.introText ?? ""} rows={2} onChange={(next) => update("introText", next)} />
      </section>

      <div className="recapTemplateGrid">
        <aside className="recapCard templateLibrary">
          <div className="sectionHeader">
            <h2>Templates</h2>
          </div>
          <div className="segmentedControl" role="tablist" aria-label="Template library">
            <button type="button" className={libraryTab === "suggested" ? "active" : ""} onClick={() => setLibraryTab("suggested")}>
              Suggested
            </button>
            <button type="button" className={libraryTab === "custom" ? "active" : ""} onClick={() => setLibraryTab("custom")}>
              Custom
            </button>
          </div>
          {libraryTab === "suggested" ? (
            <div className="templateList">
              {recapTemplates.map((template) => (
                <button
                  type="button"
                  key={template.id}
                  className={`templateListItem ${selectedTemplateId === template.id ? "active" : ""}`}
                  onClick={() => setSelectedTemplateId(template.id)}
                >
                  <span>{template.title}</span>
                  <small>{template.description}</small>
                </button>
              ))}
            </div>
          ) : (
            <p className="mutedText">Custom templates are not available yet.</p>
          )}
        </aside>

        <section className="recapCard templatePreview">
          <div className="previewHeader">
            <div>
              <h2>{selectedTemplate.title}</h2>
              <p>{selectedTemplate.id === "auto" ? "Automatically reviews the Teams meeting title and full transcript, classifies the meeting, and applies the best recap structure." : selectedTemplate.description}</p>
            </div>
            {selectedTemplate.badge && <span className="badge good">{selectedTemplate.badge}</span>}
          </div>

          {selectedTemplate.id === "auto" && (
            <section className="previewSection">
              <h3>Classification logic</h3>
              <div className="classificationGrid">
                {classificationLogic.map(([title, description]) => (
                  <div className="logicCard" key={title}>
                    <strong>{title}</strong>
                    <span>{description}</span>
                  </div>
                ))}
              </div>
            </section>
          )}

          <section className="previewSection">
            <h3>Notes structure preview</h3>
            <div className="segmentedControl previewModeControl" role="tablist" aria-label="Preview mode">
              <button type="button" className={previewMode === "standard" ? "active" : ""} onClick={() => setPreviewMode("standard")}>
                Standard
              </button>
              <button type="button" className={previewMode === "brief" ? "active" : ""} onClick={() => setPreviewMode("brief")}>
                Brief meeting
              </button>
            </div>
            <div className="teamsPreview">
              {previewMode === "standard" ? <StandardPreview selectedPreview={selectedPreview} /> : <BriefPreview />}
            </div>
          </section>

          <section className="previewSection">
            <h3>Prompt preview</h3>
            <textarea className="promptPreview" readOnly rows={10} value={promptPreview} />
          </section>

          <div className="actions">
            <button type="button" className="secondaryButton" onClick={() => update("prompt", defaultRecapPrompt)}>
              Reset to default
            </button>
            <button
              type="button"
              className="secondaryButton"
              onClick={async () => setCopyMessage(await copyPromptText(promptPreview, typeof navigator === "undefined" ? undefined : navigator.clipboard))}
            >
              Copy prompt
            </button>
            <button type="button" disabled={saving} onClick={onSave}>
              {saving ? "Saving..." : "Save recap"}
            </button>
            {copyMessage && <span className="fieldHelp">{copyMessage}</span>}
          </div>
        </section>

        <aside className="recapCard automationPanel">
          <h2>Automation</h2>
          <dl className="automationFacts">
            <div>
              <dt>Status</dt>
              <dd>{value.classificationEnabled ? "Automatic classification enabled" : "Automatic classification disabled"}</dd>
            </div>
            <div>
              <dt>Classifier input</dt>
              <dd>Teams title + full transcript</dd>
            </div>
            <div>
              <dt>Default behavior</dt>
              <dd>Apply to all meetings</dd>
            </div>
          </dl>

          <label className="check compactCheck automationToggle">
            <input type="checkbox" checked={value.classificationEnabled} onChange={(event) => update("classificationEnabled", event.target.checked)} />
            <span>Automatic classification enabled</span>
          </label>

          <section className="previewSection">
            <h3>Meeting types</h3>
            <ul className="compactList">
              <li>Weekly SPQRC</li>
              <li>Weekly Sales</li>
              <li>Individual Plant Meeting</li>
              <li>General fallback</li>
            </ul>
          </section>

          <section className="previewSection">
            <h3>Short meeting handling</h3>
            <p className="aiDisclaimer">Automatic brief recap enabled</p>
            <ul className="compactList">
              <li>Calendar or transcript duration is {value.shortMeetingDurationThresholdMinutes ?? 2} minutes or less</li>
              <li>Transcript has very little substantive discussion</li>
              <li>No full template is generated for short meetings</li>
              <li>Clear decisions and tasks are still captured</li>
            </ul>
          </section>

          <section className="previewSection">
            <h3>Recap email layout</h3>
            <div className="layoutChecks">
              {value.sections.map((section) => (
                <label className="check compactCheck" key={section.key}>
                  <input
                    type="checkbox"
                    checked={section.enabled}
                    onChange={(event) => update("sections", updateSection(value.sections, section.key, { enabled: event.target.checked }))}
                  />
                  <span>{sectionLabel(section.key)}</span>
                </label>
              ))}
            </div>
          </section>

          <section className="previewSection">
            <h3>Generation rules</h3>
            <ul className="compactList">
              <li>Strict JSON only</li>
              <li>No invented facts</li>
              <li>Owners and due dates captured when stated</li>
              <li>Missing details marked as Not specified, Unclear, or TBD</li>
            </ul>
          </section>

          <button type="button" disabled={saving} onClick={onSave}>
            {saving ? "Saving..." : "Save recap"}
          </button>
        </aside>
      </div>
    </form>
  );
}

function StandardPreview({ selectedPreview }: { selectedPreview: TemplatePreview }) {
  return (
    <>
      <p className="aiDisclaimer">Generated by AI. Be sure to check for accuracy.</p>
      <h4>Meeting notes</h4>
      <div className="teamsPreviewBlock teamsNoteBlock">
        <strong>{selectedPreview.sampleHeading}</strong>
        <p><b>{selectedPreview.sampleTitle}</b></p>
        <p>{selectedPreview.sampleDetail}</p>
      </div>
      <div className="structureList">
        {selectedPreview.meetingNoteHeadings.map((item) => (
          <span key={item}>{item}</span>
        ))}
      </div>
      <h4>Follow-up tasks</h4>
      <div className="teamsPreviewBlock teamsTaskBlock">
        <strong>{selectedPreview.sampleTaskTitle}</strong>
        <p>{selectedPreview.sampleTaskDetail} ({selectedPreview.sampleOwners})</p>
      </div>
      <div className="structureList">
        {selectedPreview.followUpTaskTitles.map((item) => (
          <span key={item}>{item}</span>
        ))}
      </div>
    </>
  );
}

function BriefPreview() {
  return (
    <>
      <p className="aiDisclaimer">Generated by AI. Be sure to check for accuracy.</p>
      <p className="briefPreviewCallout">Brief meeting detected</p>
      <h4>Meeting notes</h4>
      <div className="teamsPreviewBlock teamsNoteBlock">
        <strong>Brief meeting recap:</strong>
        <p><b>What happened:</b></p>
        <p>The recap will summarize only the limited substantive content captured in a very short meeting.</p>
        <p><b>Outcome:</b></p>
        <p>The recap will identify any clear decision or state that no substantive outcome was captured.</p>
      </div>
      <h4>Follow-up tasks</h4>
      <div className="teamsPreviewBlock teamsTaskBlock">
        <p>Only clearly stated follow-up tasks will appear.</p>
      </div>
    </>
  );
}

export function getTemplateById(id: RecapTemplateId): RecapTemplate {
  return recapTemplates.find((template) => template.id === id) ?? recapTemplates[0];
}

export function getTemplatePreview(id: RecapTemplateId): TemplatePreview {
  return templatePreviews[id] ?? templatePreviews.auto;
}

export function getPromptPreview(templateId: RecapTemplateId, savedPrompt: string): string {
  const template = getTemplateById(templateId);
  if (templateId === "auto") return `${template.prompt}\n\nCurrent saved prompt:\n${savedPrompt}`;
  return `${template.prompt}\n\nCurrent saved prompt:\n${savedPrompt}`;
}

export async function copyPromptText(
  prompt: string,
  clipboard?: Pick<Clipboard, "writeText">
): Promise<"Prompt copied" | "Clipboard unavailable"> {
  if (!clipboard?.writeText) return "Clipboard unavailable";
  await clipboard.writeText(prompt);
  return "Prompt copied";
}

export function updateSection(
  sections: RecapSettings["sections"],
  key: RecapSectionKey,
  patch: Partial<RecapSettings["sections"][number]>
): RecapSettings["sections"] {
  return sections.map((section) => (section.key === key ? { ...section, ...patch } : section));
}

function sectionLabel(key: RecapSectionKey): string {
  return {
    summary: "Summary",
    decisions: "Decisions",
    actionItems: "Action items",
    openQuestions: "Open questions",
    risks: "Risks",
    followUps: "Follow-ups"
  }[key];
}

function Field({
  label,
  placeholder,
  value,
  onChange
}: {
  label: string;
  placeholder?: string;
  value: string;
  onChange: (value: string) => void;
}) {
  return (
    <label>
      <span>{label}</span>
      <input placeholder={placeholder} value={value} onChange={(event) => onChange(event.target.value)} />
    </label>
  );
}

function TextAreaField({
  label,
  rows,
  value,
  onChange
}: {
  label: string;
  rows: number;
  value: string;
  onChange: (value: string) => void;
}) {
  return (
    <label>
      <span>{label}</span>
      <textarea rows={rows} value={value} onChange={(event) => onChange(event.target.value)} />
    </label>
  );
}
