import { useState } from "react";
import { defaultRecapPrompt, type AppSettings, type RecapSectionKey } from "@minutesbot/shared";

type RecapSettings = AppSettings["recap"];
export type RecapTemplateId = "universal";

type RecapTemplate = {
  id: RecapTemplateId;
  title: string;
  description: string;
  badge?: string;
  structure: string[];
  prompt: string;
};

type TemplatePreview = {
  meetingNoteHeadings: string[];
  followUpTaskTitles: string[];
  sampleHeading: string;
  sampleTitle: string;
  sampleDetail: string;
  sampleTaskTitle: string;
  sampleTaskDetail: string;
  sampleOwners: string;
};

type PreviewMode = "standard" | "brief";

const universalPromptPreview = [
  "Generator prompt: apply one universal WGS recap template to every Teams meeting.",
  "Return strict JSON only, do not invent facts, clean up unclear speaker labels, and build one layered recap with Executive Highlights, Person-Specific Briefs, Notes, Action Items, Decisions, Risks / Blockers, Open Questions, and Reference Notes."
].join("\n\n");

export const recapTemplates: RecapTemplate[] = [
  {
    id: "universal",
    title: "Universal WGS recap",
    badge: "ACTIVE DEFAULT",
    description: "Single executive recap structure used for every meeting, with emphasis adapted from the transcript content.",
    structure: ["Generated by AI disclaimer", "Meeting metadata", "Executive highlights", "Person-specific briefs", "Notes", "Action items", "Decisions", "Risks / blockers", "Open questions", "Reference notes"],
    prompt: universalPromptPreview
  }
];

const templatePreviews: Record<RecapTemplateId, TemplatePreview> = {
  universal: {
    meetingNoteHeadings: ["1. Executive Highlights", "2. Person-Specific Briefs", "3. Notes", "4. Action Items", "5. Decisions", "6. Risks / Blockers", "7. Open Questions", "8. Reference Notes"],
    followUpTaskTitles: ["Highest-priority follow-ups", "Owner commitments", "Customer or stakeholder follow-ups", "Open decision checks", "Next-meeting topics"],
    sampleHeading: "1. Executive Highlights:",
    sampleTitle: "High-impact headlines:",
    sampleDetail: "The recap will rank the most important business impact, execution impact, decisions, risks, and next steps before general meeting context.",
    sampleTaskTitle: "4. Action Items:",
    sampleTaskDetail: "Group concrete deduplicated follow-ups by owner with due timing, priority, related area, and useful notes when stated.",
    sampleOwners: "assigned owners"
  }
};

export function RecapForm({
  value,
  onChange,
  onSave,
  saving = false
}: {
  value: RecapSettings;
  onChange: (recap: RecapSettings) => void;
  onSave?: () => void | Promise<void>;
  saving?: boolean;
}) {
  const [previewMode, setPreviewMode] = useState<PreviewMode>("standard");
  const [copyMessage, setCopyMessage] = useState("");
  const selectedTemplate = getTemplateById("universal");
  const selectedPreview = getTemplatePreview("universal");
  const update = <K extends keyof RecapSettings>(key: K, next: RecapSettings[K]) => onChange({ ...value, [key]: next });
  const promptPreview = getPromptPreview(selectedTemplate.id, value.prompt);

  return (
    <form className="recapTemplatePage">
      <section className="recapSettingsStrip" aria-label="Recap settings">
        <Field label="Subject prefix" value={value.subjectPrefix} onChange={(next) => update("subjectPrefix", next)} />
        <TextAreaField label="Intro text" value={value.introText ?? ""} rows={2} onChange={(next) => update("introText", next)} />
      </section>

      <div className="recapTemplateGrid">
        <aside className="recapCard templateLibrary">
          <div className="sectionHeader">
            <h2>Universal template</h2>
          </div>
          <div className="templateList">
            {recapTemplates.map((template) => (
              <div key={template.id} className="templateListItem active">
                <span>{template.title}</span>
                <small>{template.description}</small>
              </div>
            ))}
          </div>
          <section className="previewSection">
            <h3>Template scope</h3>
            <ul className="compactList">
              <li>Applied to all meetings</li>
              <li>Adapts emphasis from transcript content</li>
              <li>Does not run meeting-type classification</li>
              <li>Keeps one recap structure for every meeting</li>
            </ul>
          </section>
        </aside>

        <section className="recapCard templatePreview">
          <div className="previewHeader">
            <div>
              <h2>{selectedTemplate.title}</h2>
              <p>{selectedTemplate.description}</p>
            </div>
            {selectedTemplate.badge && <span className="badge good">{selectedTemplate.badge}</span>}
          </div>

          <section className="previewSection">
            <h3>Notes structure preview</h3>
            <div className="segmentedControl previewModeControl" role="tablist" aria-label="Preview mode">
              <button type="button" className={previewMode === "standard" ? "active" : ""} onClick={() => setPreviewMode("standard")}>
                Standard
              </button>
              <button type="button" className={previewMode === "brief" ? "active" : ""} onClick={() => setPreviewMode("brief")}>
                Brief meeting
              </button>
            </div>
            <div className="teamsPreview">
              {previewMode === "standard" ? <StandardPreview selectedPreview={selectedPreview} /> : <BriefPreview />}
            </div>
          </section>

          <section className="previewSection">
            <h3>Prompt preview</h3>
            <textarea className="promptPreview" readOnly rows={10} value={promptPreview} />
          </section>

          <div className="actions">
            <button type="button" className="secondaryButton" onClick={() => update("prompt", defaultRecapPrompt)}>
              Reset to WGS default
            </button>
            <button
              type="button"
              className="secondaryButton"
              onClick={async () => setCopyMessage(await copyPromptText(promptPreview, typeof navigator === "undefined" ? undefined : navigator.clipboard))}
            >
              Copy prompt
            </button>
            <button type="button" disabled={saving} onClick={onSave}>
              {saving ? "Saving..." : "Save recap"}
            </button>
            {copyMessage && <span className="fieldHelp">{copyMessage}</span>}
          </div>
        </section>

        <aside className="recapCard automationPanel">
          <h2>Automation</h2>
          <dl className="automationFacts">
            <div>
              <dt>Status</dt>
              <dd>Single template applied to all meetings</dd>
            </div>
            <div>
              <dt>Template input</dt>
              <dd>Teams title + full transcript</dd>
            </div>
            <div>
              <dt>Default behavior</dt>
              <dd>Use universal recap structure</dd>
            </div>
          </dl>

          <section className="previewSection">
            <h3>Content emphasis</h3>
            <ul className="compactList">
              <li>Business impact and execution impact first</li>
              <li>Decisions, risks, blockers, and next steps before context</li>
              <li>Topic labels selected from the meeting content</li>
              <li>Empty or irrelevant sections omitted when possible</li>
            </ul>
          </section>

          <section className="previewSection">
            <h3>Short meeting handling</h3>
            <p className="aiDisclaimer">Automatic brief recap enabled</p>
            <ul className="compactList">
              <li>Calendar or transcript duration is {value.shortMeetingDurationThresholdMinutes ?? 2} minutes or less</li>
              <li>Transcript has very little substantive discussion</li>
              <li>No long recap is generated for short meetings</li>
              <li>Clear decisions and tasks are still captured</li>
            </ul>
          </section>

          <section className="previewSection">
            <h3>Recap email layout</h3>
            <div className="layoutChecks">
              {value.sections.map((section) => (
                <label className="check compactCheck" key={section.key}>
                  <input
                    type="checkbox"
                    checked={section.enabled}
                    onChange={(event) => update("sections", updateSection(value.sections, section.key, { enabled: event.target.checked }))}
                  />
                  <span>{sectionLabel(section.key)}</span>
                </label>
              ))}
            </div>
          </section>

          <section className="previewSection">
            <h3>Generation rules</h3>
            <ul className="compactList">
              <li>Strict JSON only</li>
              <li>No invented facts</li>
              <li>Owners and due dates captured when stated</li>
              <li>Missing details marked as Not specified, Unclear, or TBD</li>
            </ul>
          </section>

          <button type="button" disabled={saving} onClick={onSave}>
            {saving ? "Saving..." : "Save recap"}
          </button>
        </aside>
      </div>
    </form>
  );
}

function StandardPreview({ selectedPreview }: { selectedPreview: TemplatePreview }) {
  return (
    <>
      <p className="aiDisclaimer">Generated by AI. Be sure to check for accuracy.</p>
      <h4>Meeting notes</h4>
      <div className="teamsPreviewBlock teamsNoteBlock">
        <strong>{selectedPreview.sampleHeading}</strong>
        <p><b>{selectedPreview.sampleTitle}</b></p>
        <p>{selectedPreview.sampleDetail}</p>
      </div>
      <div className="structureList">
        {selectedPreview.meetingNoteHeadings.map((item) => (
          <span key={item}>{item}</span>
        ))}
      </div>
      <h4>Follow-up tasks</h4>
      <div className="teamsPreviewBlock teamsTaskBlock">
        <strong>{selectedPreview.sampleTaskTitle}</strong>
        <p>{selectedPreview.sampleTaskDetail} ({selectedPreview.sampleOwners})</p>
      </div>
      <div className="structureList">
        {selectedPreview.followUpTaskTitles.map((item) => (
          <span key={item}>{item}</span>
        ))}
      </div>
    </>
  );
}

function BriefPreview() {
  return (
    <>
      <p className="aiDisclaimer">Generated by AI. Be sure to check for accuracy.</p>
      <p className="briefPreviewCallout">Brief meeting detected</p>
      <h4>Meeting notes</h4>
      <div className="teamsPreviewBlock teamsNoteBlock">
        <strong>Brief meeting recap:</strong>
        <p><b>What happened:</b></p>
        <p>The recap will summarize only the limited substantive content captured in a very short meeting.</p>
        <p><b>Outcome:</b></p>
        <p>The recap will identify any clear decision or state that no substantive outcome was captured.</p>
      </div>
      <h4>Follow-up tasks</h4>
      <div className="teamsPreviewBlock teamsTaskBlock">
        <p>Only clearly stated follow-up tasks will appear.</p>
      </div>
    </>
  );
}

export function getTemplateById(id: RecapTemplateId): RecapTemplate {
  return recapTemplates.find((template) => template.id === id) ?? recapTemplates[0];
}

export function getTemplatePreview(id: RecapTemplateId): TemplatePreview {
  return templatePreviews[id] ?? templatePreviews.universal;
}

export function getPromptPreview(templateId: RecapTemplateId, savedPrompt: string): string {
  const template = getTemplateById(templateId);
  return `${template.prompt}\n\nCurrent saved prompt:\n${savedPrompt}`;
}

export async function copyPromptText(
  prompt: string,
  clipboard?: Pick<Clipboard, "writeText">
): Promise<"Prompt copied" | "Clipboard unavailable"> {
  if (!clipboard?.writeText) return "Clipboard unavailable";
  await clipboard.writeText(prompt);
  return "Prompt copied";
}

export function updateSection(
  sections: RecapSettings["sections"],
  key: RecapSectionKey,
  patch: Partial<RecapSettings["sections"][number]>
): RecapSettings["sections"] {
  return sections.map((section) => (section.key === key ? { ...section, ...patch } : section));
}

export function moveSection(sections: RecapSettings["sections"], index: number, delta: -1 | 1): RecapSettings["sections"] {
  const nextIndex = index + delta;
  if (nextIndex < 0 || nextIndex >= sections.length) return sections;
  const copy = [...sections];
  const [item] = copy.splice(index, 1);
  copy.splice(nextIndex, 0, item);
  return copy;
}

function sectionLabel(key: RecapSectionKey): string {
  return {
    summary: "Summary",
    decisions: "Decisions",
    actionItems: "Action items",
    openQuestions: "Open questions",
    risks: "Risks",
    followUps: "Follow-ups"
  }[key];
}

function Field({
  label,
  placeholder,
  value,
  onChange
}: {
  label: string;
  placeholder?: string;
  value: string;
  onChange: (value: string) => void;
}) {
  return (
    <label>
      <span>{label}</span>
      <input placeholder={placeholder} value={value} onChange={(event) => onChange(event.target.value)} />
    </label>
  );
}

function TextAreaField({
  label,
  rows,
  value,
  onChange
}: {
  label: string;
  rows: number;
  value: string;
  onChange: (value: string) => void;
}) {
  return (
    <label>
      <span>{label}</span>
      <textarea rows={rows} value={value} onChange={(event) => onChange(event.target.value)} />
    </label>
  );
}
