import { describe, expect, it } from "vitest";
import { defaultSettings } from "@minutesbot/shared";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import {
  RecapForm,
  copyPromptText,
  getPromptPreview,
  getTemplatePreview,
  recapTemplates,
  updateSection
} from "./RecapForm";

describe("recap form helpers", () => {
  it("updates section labels without mutating the original array", () => {
    const sections = defaultSettings.recap.sections;
    const next = updateSection(sections, "summary", { label: "Overview", enabled: false });

    expect(next.find((section) => section.key === "summary")).toMatchObject({ label: "Overview", enabled: false });
    expect(sections.find((section) => section.key === "summary")).toMatchObject({ label: "Summary", enabled: true });
  });

  it("defines the five suggested recap templates", () => {
    expect(recapTemplates.map((template) => template.title)).toEqual([
      "Auto-classified recap",
      "Weekly SPQRC",
      "Weekly Sales",
      "Individual Plant Meeting",
      "General"
    ]);
    expect(getTemplatePreview("weekly_sales").meetingNoteHeadings).toContain("Sales Pipeline and Forecast Updates");
    expect(getPromptPreview("auto", defaultSettings.recap.prompt)).toContain("classifier");
  });

  it("renders the recap template management surface", () => {
    const html = renderToStaticMarkup(React.createElement(RecapForm, { value: defaultSettings.recap, onChange: () => undefined }));

    expect(html).toContain("Templates");
    expect(html).toContain("Auto-classified recap");
    expect(html).toContain("Weekly SPQRC");
    expect(html).toContain("Weekly Sales");
    expect(html).toContain("Individual Plant Meeting");
    expect(html).toContain("General");
    expect(html).toContain("Automation");
    expect(html).toContain("Automatic classification enabled");
    expect(html).toContain("Generated by AI. Be sure to check for accuracy.");
    expect(html).toContain("Preview mode");
    expect(html).toContain("Brief meeting");
    expect(html).toContain("Meeting notes");
    expect(html).toContain("Follow-up tasks");
    expect(html).toContain("Short meeting handling");
    expect(html).toContain("Automatic brief recap enabled");
    expect(html).toContain("No full template is generated for short meetings");
    expect(html).toContain("Prompt preview");
    expect(html).toContain("Copy prompt");
    expect(html).toContain("Save recap");
  });

  it("returns teams-style preview headings for each template", () => {
    expect(getTemplatePreview("weekly_spqrc").meetingNoteHeadings).toContain("Safety Updates");
    expect(getTemplatePreview("weekly_sales").meetingNoteHeadings).toContain("Quotes and Pricing Updates");
    expect(getTemplatePreview("plant_meeting").meetingNoteHeadings).toContain("Maintenance, Equipment, and Materials");
    expect(getTemplatePreview("general").meetingNoteHeadings).toContain("Risks and Open Issues");
  });

  it("copies prompt text when clipboard is available", async () => {
    const writes: string[] = [];
    const clipboard = {
      async writeText(value: string) {
        writes.push(value);
      }
    };

    await expect(copyPromptText("prompt text", clipboard)).resolves.toBe("Prompt copied");
    expect(writes).toEqual(["prompt text"]);
  });
});
