import { meetingRecapTypeLabels, type MeetingRecapType } from "./meetingTypes";
import type { SummaryInput } from "./types";

export function buildSummaryPrompt(input: SummaryInput): string {
  const meetingType = input.meetingType ?? "general";
  const recapDepth = input.recapDepth ?? "standard";
  return [
    buildBaseInstructions(input.prompt),
    `Meeting: ${input.meetingSubject}`,
    input.meetingStartTime ? `Start time: ${input.meetingStartTime}` : "",
    input.meetingEndTime ? `End time: ${input.meetingEndTime}` : "",
    input.meetingDurationMinutes !== undefined ? `Meeting duration minutes: ${input.meetingDurationMinutes}` : "",
    input.transcriptDurationMinutes !== undefined ? `Transcript duration minutes: ${input.transcriptDurationMinutes}` : "",
    input.speakerTurnCount !== undefined ? `Speaker turn count: ${input.speakerTurnCount}` : "",
    input.wordCount !== undefined ? `Word count: ${input.wordCount}` : "",
    input.organizerEmail ? `Organizer: ${input.organizerEmail}` : "",
    `Attendees: ${input.attendees.map((attendee) => attendee.name ? `${attendee.name} <${attendee.email}>` : attendee.email).join(", ")}`,
    `Resolved meeting type: ${meetingType}`,
    `Resolved recap depth: ${recapDepth}`,
    buildRecapDepthInstructions(recapDepth, meetingType),
    "JSON shape: {\"meetingType\":\"weekly_spqrc\"|\"weekly_sales\"|\"plant_meeting\"|\"general\",\"recapDepth\":\"brief\"|\"standard\",\"executiveRecap\":{\"topPriorities\":[{\"title\":\"string\",\"summary\":\"string\",\"whyItMatters\":\"string\",\"owner\":\"string\",\"nextStep\":\"string\",\"dueDate\":\"string\"}],\"immediateActions\":[{\"priority\":\"string\",\"action\":\"string\",\"owner\":\"string\",\"due\":\"string\",\"relatedCustomerOrArea\":\"string\",\"status\":\"string\"}],\"keyDecisions\":[{\"decision\":\"string\",\"impact\":\"string\",\"ownerOrFollowUp\":\"string\"}],\"majorRisks\":[{\"title\":\"string\",\"explanation\":\"string\",\"impact\":\"string\",\"mitigationOrNextStep\":\"string\"}],\"detailedRecap\":[{\"heading\":\"string\",\"summary\":\"string\"}],\"winsAndProgress\":[{\"title\":\"string\",\"detail\":\"string\",\"impact\":\"string\"}],\"fullActionRegister\":[{\"action\":\"string\",\"owner\":\"string\",\"due\":\"string\",\"priority\":\"High\"|\"Medium\"|\"Low\",\"relatedArea\":\"string\",\"notes\":\"string\"}],\"openQuestions\":[{\"question\":\"string\",\"whyItMatters\":\"string\",\"ownerOrBestNextStep\":\"string\"}],\"referenceNotes\":[{\"topic\":\"string\",\"notes\":[\"string\"]}]},\"meetingNotes\":[{\"heading\":\"string\",\"overview\":\"string\",\"items\":[{\"title\":\"string\",\"detail\":\"string\"}]}],\"followUpTasks\":[{\"title\":\"string\",\"description\":\"string\",\"owners\":[\"string\"],\"dueDate\":\"string\"}],\"summary\":string[],\"decisions\":string[],\"actionItems\":[{\"owner\":\"string\",\"task\":\"string\",\"dueDate\":\"string\"}],\"openQuestions\":string[],\"risks\":string[],\"followUps\":string[]}",
    "Transcript:",
    input.transcriptText
  ]
    .filter(Boolean)
    .join("\n");
}

function buildBaseInstructions(customPrompt?: string): string {
  return [
    customPrompt,
    "You are generating a WGS / MinutesBot meeting recap in a polished business format.",
    "First respect the provided recapDepth.",
    "The renderer displays this disclaimer at the top: Generated by AI. Be sure to check for accuracy. Do not include this disclaimer in any JSON field.",
    "Return strict JSON only.",
    "Return strict JSON only using the required schema.",
    "Do not return markdown, code fences, prose, comments, or extra keys.",
    "Do not invent facts, owners, deadlines, decisions, risks, metrics, customer names, plant names, or follow-ups.",
    "If something is unclear, say \"Unclear\".",
    "If something is not mentioned, say \"Not specified\".",
    "If there are no items for a field, return an empty array.",
    "Use the resolved meeting type provided by the classifier.",
    "Do not reclassify the meeting during recap generation.",
    "Use the resolved recap depth provided by the classifier.",
    "Do not change recapDepth during recap generation.",
    "Preserve important names, locations, customers, plants, systems, deadlines, and metrics when stated.",
    "Be concise and action-oriented.",
    "Prioritize what changed, what was decided, who owns what, and what must happen next.",
    "Avoid verbatim quotes unless the exact wording is critical.",
    "Use plain business language suitable for an email recap.",
    "For recapDepth brief, generate a concise recap for a very short meeting. Do not create a full topic-grouped recap. Do not infer a large agenda from minimal content. Include only what was actually captured. Clearly state when no substantive content, decisions, or follow-up tasks were captured. Keep the recap short. Do not pad short meetings.",
    "For recapDepth standard, generate one unified executive recap. Do not organize by transcript chunk. Do not emit repeated Weekly Summary sections.",
    "For standard recaps, model this structure in executiveRecap:",
    "# {Meeting Name} — Executive Recap",
    "{Meeting Date / Time}",
    "AI-generated recap. Review for accuracy.",
    "## 1. At a Glance",
    "### Top Priorities",
    "List 5 to 7 maximum. Rank by business importance, not transcript order. Use title, summary, whyItMatters, owner, nextStep, and dueDate.",
    "Priority ranking order: customer-impacting blockers, revenue or collections or quote activity, staffing and capacity risks, decisions, named-owner or near-term actions, delivery risks, and execution-blocking open questions.",
    "### Immediate Actions",
    "Include only urgent, customer-facing, revenue-related, or blocker-removal actions. Use this table shape: | Priority | Action | Owner | Due | Related Customer / Area | Status |. Do not list more than 10.",
    "### Key Decisions",
    "Include only actual decisions or clear commitments. If no clear decisions were confirmed, leave executiveRecap.keyDecisions empty and put No clear decisions were confirmed in the transcript in decisions only if useful for legacy compatibility.",
    "### Major Risks / Blockers",
    "List only the 3 to 7 most important risks with explanation, impact, and mitigationOrNextStep.",
    "## 2. Detailed Recap",
    "Organize detailedRecap by business topic, not transcript order. Use only relevant sections from Customer Work & Sales Pipeline, Staffing, Capacity & Operations, Reporting, CRM & Tracking, Documentation & Process Control, Financial / Pricing / Contract Items, and Wins & Progress.",
    "## 3. Full Action Register",
    "Populate fullActionRegister with the complete deduplicated task list. Priority values must be High, Medium, or Low. Convert relative due dates using the meeting date when possible; otherwise use TBD.",
    "## 4. Open Questions",
    "Populate executiveRecap.openQuestions only with unresolved items that affect execution, customer communication, staffing, revenue, reporting, or accountability.",
    "## 5. Reference Notes",
    "Use referenceNotes for lower-priority traceability details grouped by topic. Keep notes brief.",
    "For standard recaps, also populate meetingNotes for backward compatibility using at most these headings when supported: 1. At a Glance:, 2. Detailed Recap:, 5. Reference Notes:. Do not duplicate the same detail across meetingNotes items.",
    "For standard recaps, each meetingNotes heading should end with a colon. Each subtopic title should be concise and each detail should be 1 to 2 sentences.",
    "Clean up unclear speaker labels such as \"Conference Room Computer\". Attribute to a named speaker only when the transcript supports it; otherwise write without that speaker label.",
    "If a one-word weekly focus is stated, include it in the summary and preserve the exact word.",
    "Action items must be concrete and execution-focused. Each action item must include owner, task, and dueDate. Use owner \"Unassigned\" and dueDate \"TBD\" when not specified.",
    "followUpTasks must mirror the Teams format. Each follow-up task must include title, description, owners, and dueDate. Use owners [\"Unassigned\"] and dueDate \"TBD\" when not specified.",
    "Do not create a follow-up task unless the transcript supports it.",
    "Populate actionItems with one action item for each followUpTasks item when appropriate. Use owner as comma-separated owners or \"Unassigned\", task as the same core task as followUpTasks.description, and dueDate as the same dueDate.",
    "Merge duplicate action items.",
    "Deduplicate similar actions, risks, decisions, open questions, follow-ups, priorities, and reference notes across transcript chunks.",
    "Populate summary with 4 to 8 concise executive bullets for compatibility. Capture top priorities, key business impacts, major risks, revenue or operating impact, and any stated one-word weekly focus.",
    "Capture action items related to safety follow-up, quality issue closure, delivery or customer response, cost reduction, sales or customer follow-up, quote or pricing work, plant operational improvements, open issues, and data or reporting needed before the next meeting.",
    "Do not convert general discussion into action items unless an action was clearly assigned or strongly implied.",
    "Only include confirmed decisions, agreements, approvals, rejected options, committed plans, or direction changes. Do not treat discussion as a decision unless there was clear agreement.",
    "Risks must capture blockers, delays, safety risks, quality risks, delivery risks, cost risks, customer or revenue risks, staffing risks, equipment or material constraints, and dependencies.",
    "Open questions must capture unresolved questions, missing information, unclear ownership, unclear deadlines, pending customer answers, pending plant data, or unanswered operational concerns.",
    "Follow-ups must capture planned future meetings, customer follow-ups, plant check-ins, internal reviews, reports to prepare, data to validate, or topics to revisit in the next weekly meeting."
  ]
    .filter(Boolean)
    .join("\n");
}

function buildRecapDepthInstructions(recapDepth: NonNullable<SummaryInput["recapDepth"]>, meetingType: MeetingRecapType): string {
  if (recapDepth === "brief") {
    return [
      "recapDepth is brief.",
      "Generate a simplified short-meeting recap using the resolved meeting type only as context.",
      "Do not use the full standard template structure.",
      "Do not create fake sections like Safety, Sales, Plant, Cost, or Quality unless the short meeting actually discussed them.",
      "meetingNotes must contain exactly 1 heading: Brief meeting recap.",
      "meetingNotes[0].items must contain at most 2 items titled What happened and Outcome.",
      "summary must contain 1 to 3 bullets.",
      "followUpTasks must contain only real tasks supported by the transcript.",
      "decisions must contain only confirmed decisions.",
      "risks should usually be empty unless a real risk was stated.",
      "openQuestions should include transcript limitations if relevant.",
      "If the transcript is mostly empty, joining chatter, bot setup, or low quality, say so clearly instead of inventing notes.",
      "For a short meeting with a real decision or assigned action, keep recapDepth brief and include that decision or action clearly."
    ].join("\n");
  }
  return [
    "recapDepth is standard.",
    "Generate one executive recap with At a Glance first, detailed business-topic context second, then the full action register, open questions, and reference notes.",
    buildMeetingTypeSummaryInstructions(meetingType)
  ].join("\n");
}

export function buildMeetingTypeSummaryInstructions(meetingType: MeetingRecapType): string {
  const instructions: Record<MeetingRecapType, string[]> = {
    weekly_spqrc: [
      "For weekly_spqrc, prefer meetingNotes headings like these when supported by the transcript:",
      "Executive Summary",
      "Safety, People, Quality, Delivery, and Cost Updates",
      "Plant Operations Reports",
      "Customer or Sales Updates",
      "Compliance or Program Updates",
      "Decisions and Announcements",
      "Risks and Blockers",
      "Open Questions"
    ],
    weekly_sales: [
      "For weekly_sales, prioritize customer follow-ups, quote movement, revenue or collections, pipeline health, CRM/reporting gaps, staffing or capacity constraints, pricing or contract concerns, decisions, risks, and open execution questions.",
      "For weekly_sales, executiveRecap.detailedRecap should use business-topic headings such as Customer Work & Sales Pipeline, Staffing, Capacity & Operations, Reporting, CRM & Tracking, Documentation & Process Control, Financial / Pricing / Contract Items, and Wins & Progress when supported.",
      "For weekly_sales, keep followUpTasks, actionItems, immediateActions, and fullActionRegister aligned without duplicates."
    ],
    plant_meeting: [
      "For plant_meeting, prefer meetingNotes headings like these when supported by the transcript:",
      "Executive Summary",
      "Plant Operations and Safety Reports",
      "Production, Schedule, and Customer Updates",
      "Quality and Customer Issues",
      "Maintenance, Equipment, and Material Constraints",
      "Staffing and Operational Updates",
      "Cost, Productivity, and Efficiency",
      "Decisions",
      "Risks and Blockers",
      "Open Questions"
    ],
    general: [
      "For general, prefer meetingNotes headings like these when supported by the transcript:",
      "Executive Summary",
      "Key Discussion Topics",
      "Project or Business Updates",
      "Operational Updates",
      "Customer or Stakeholder Updates",
      "Decisions",
      "Risks and Blockers",
      "Open Questions"
    ]
  };
  return [`Summary template label: ${meetingRecapTypeLabels[meetingType]}`, ...instructions[meetingType], "Only include headings that are supported by the transcript."].join("\n");
}
