import { meetingRecapTypeLabels, type MeetingRecapType } from "./meetingTypes";
import type { SummaryInput } from "./types";

export function buildSummaryPrompt(input: SummaryInput): string {
  const meetingType = input.meetingType ?? "general";
  const recapDepth = input.recapDepth ?? "standard";
  return [
    buildBaseInstructions(input.prompt),
    `Meeting: ${input.meetingSubject}`,
    input.meetingStartTime ? `Start time: ${input.meetingStartTime}` : "",
    input.meetingEndTime ? `End time: ${input.meetingEndTime}` : "",
    input.meetingDurationMinutes !== undefined ? `Meeting duration minutes: ${input.meetingDurationMinutes}` : "",
    input.transcriptDurationMinutes !== undefined ? `Transcript duration minutes: ${input.transcriptDurationMinutes}` : "",
    input.speakerTurnCount !== undefined ? `Speaker turn count: ${input.speakerTurnCount}` : "",
    input.wordCount !== undefined ? `Word count: ${input.wordCount}` : "",
    input.organizerEmail ? `Organizer: ${input.organizerEmail}` : "",
    `Attendees: ${input.attendees.map((attendee) => attendee.name ? `${attendee.name} <${attendee.email}>` : attendee.email).join(", ")}`,
    `Resolved meeting type: ${meetingType}`,
    `Resolved recap depth: ${recapDepth}`,
    buildRecapDepthInstructions(recapDepth, meetingType),
    "JSON shape: {\"meetingType\":\"weekly_spqrc\"|\"weekly_sales\"|\"plant_meeting\"|\"general\",\"recapDepth\":\"brief\"|\"standard\",\"meetingNotes\":[{\"heading\":\"string\",\"overview\":\"string\",\"items\":[{\"title\":\"string\",\"detail\":\"string\"}]}],\"followUpTasks\":[{\"title\":\"string\",\"description\":\"string\",\"owners\":[\"string\"],\"dueDate\":\"string\"}],\"summary\":string[],\"decisions\":string[],\"actionItems\":[{\"owner\":\"string\",\"task\":\"string\",\"dueDate\":\"string\"}],\"openQuestions\":string[],\"risks\":string[],\"followUps\":string[]}",
    "Transcript:",
    input.transcriptText
  ]
    .filter(Boolean)
    .join("\n");
}

function buildBaseInstructions(customPrompt?: string): string {
  return [
    customPrompt,
    "You are generating a WGS / MinutesBot meeting recap in a polished business format.",
    "First respect the provided recapDepth.",
    "The renderer displays this disclaimer at the top: Generated by AI. Be sure to check for accuracy. Do not include this disclaimer in any JSON field.",
    "Return strict JSON only.",
    "Return strict JSON only using the required schema.",
    "Do not return markdown, code fences, prose, comments, or extra keys.",
    "Do not invent facts, owners, deadlines, decisions, risks, metrics, customer names, plant names, or follow-ups.",
    "If something is unclear, say \"Unclear\".",
    "If something is not mentioned, say \"Not specified\".",
    "If there are no items for a field, return an empty array.",
    "Use the resolved meeting type provided by the classifier.",
    "Do not reclassify the meeting during recap generation.",
    "Use the resolved recap depth provided by the classifier.",
    "Do not change recapDepth during recap generation.",
    "Preserve important names, locations, customers, plants, systems, deadlines, and metrics when stated.",
    "Be concise and action-oriented.",
    "Prioritize what changed, what was decided, who owns what, and what must happen next.",
    "Avoid verbatim quotes unless the exact wording is critical.",
    "Use plain business language suitable for an email recap.",
    "For recapDepth brief, generate a concise recap for a very short meeting. Do not create a full topic-grouped recap. Do not infer a large agenda from minimal content. Include only what was actually captured. Clearly state when no substantive content, decisions, or follow-up tasks were captured. Keep the recap short. Do not pad short meetings.",
    "For recapDepth standard, generate the full WGS / MinutesBot meeting recap using the section order from the resolved meeting type template.",
    "For standard recaps, write meetingNotes as grouped topical notes. Each meetingNotes heading should match a supported template section. Under each heading, create specific titled items with paragraph details.",
    "For standard recaps, each meetingNotes heading should end with a colon. Each subtopic title should be concise and each detail should be a complete paragraph, usually 1 to 2 sentences.",
    "For standard recaps, include 2 to 7 subtopic items under each major heading when the transcript supports them. Include speaker names, plant names, customer names, programs, systems, locations, deadlines, and metrics when stated.",
    "Clean up unclear speaker labels such as \"Conference Room Computer\". Attribute to a named speaker only when the transcript supports it; otherwise write without that speaker label.",
    "If a one-word weekly focus is stated, include it in the summary and preserve the exact word.",
    "Use this style as formatting guidance only:",
    "Meeting notes:",
    "Hearing Conservation Program Updates:",
    "Annual Noise Monitoring:",
    "Jenny instructed all plants to check noise levels at least annually using a sound monitoring device or approved mobile apps, ensuring multiple areas are tested throughout each facility.",
    "Plant Operations and Safety Reports:",
    "Athens Plant Safety and Production:",
    "Tyler reported two recordables, new goggles ordered, strong retention and attendance, no customer issues, and continued focus on maximizing hours worked.",
    "Follow-up tasks:",
    "Employee Experience Survey:",
    "Survey all current employees at each plant using the Employee Experience Survey form and return completed forms by the stated deadline. (all plant managers)",
    "Do not copy this example content unless it appears in the transcript. Use it only as formatting guidance.",
    "Action items must be concrete and execution-focused. Each action item must include owner, task, and dueDate. Use owner \"Unassigned\" and dueDate \"TBD\" when not specified.",
    "followUpTasks must mirror the Teams format. Each follow-up task must include title, description, owners, and dueDate. Use owners [\"Unassigned\"] and dueDate \"TBD\" when not specified.",
    "Do not create a follow-up task unless the transcript supports it.",
    "Populate actionItems with one action item for each followUpTasks item when appropriate. Use owner as comma-separated owners or \"Unassigned\", task as the same core task as followUpTasks.description, and dueDate as the same dueDate.",
    "Populate summary with 4 to 8 concise Weekly Summary bullets for compatibility. Capture meeting focus, key themes, progress, major risks, revenue or operating impact, and any stated one-word weekly focus.",
    "Capture action items related to safety follow-up, quality issue closure, delivery or customer response, cost reduction, sales or customer follow-up, quote or pricing work, plant operational improvements, open issues, and data or reporting needed before the next meeting.",
    "Do not convert general discussion into action items unless an action was clearly assigned or strongly implied.",
    "Only include confirmed decisions, agreements, approvals, rejected options, committed plans, or direction changes. Do not treat discussion as a decision unless there was clear agreement.",
    "Risks must capture blockers, delays, safety risks, quality risks, delivery risks, cost risks, customer or revenue risks, staffing risks, equipment or material constraints, and dependencies.",
    "Open questions must capture unresolved questions, missing information, unclear ownership, unclear deadlines, pending customer answers, pending plant data, or unanswered operational concerns.",
    "Follow-ups must capture planned future meetings, customer follow-ups, plant check-ins, internal reviews, reports to prepare, data to validate, or topics to revisit in the next weekly meeting."
  ]
    .filter(Boolean)
    .join("\n");
}

function buildRecapDepthInstructions(recapDepth: NonNullable<SummaryInput["recapDepth"]>, meetingType: MeetingRecapType): string {
  if (recapDepth === "brief") {
    return [
      "recapDepth is brief.",
      "Generate a simplified short-meeting recap using the resolved meeting type only as context.",
      "Do not use the full standard template structure.",
      "Do not create fake sections like Safety, Sales, Plant, Cost, or Quality unless the short meeting actually discussed them.",
      "meetingNotes must contain exactly 1 heading: Brief meeting recap.",
      "meetingNotes[0].items must contain at most 2 items titled What happened and Outcome.",
      "summary must contain 1 to 3 bullets.",
      "followUpTasks must contain only real tasks supported by the transcript.",
      "decisions must contain only confirmed decisions.",
      "risks should usually be empty unless a real risk was stated.",
      "openQuestions should include transcript limitations if relevant.",
      "If the transcript is mostly empty, joining chatter, bot setup, or low quality, say so clearly instead of inventing notes.",
      "For a short meeting with a real decision or assigned action, keep recapDepth brief and include that decision or action clearly."
    ].join("\n");
  }
  return [
    "recapDepth is standard.",
    "Generate the full WGS / MinutesBot meeting recap with grouped Meeting notes and Follow-up tasks.",
    buildMeetingTypeSummaryInstructions(meetingType)
  ].join("\n");
}

export function buildMeetingTypeSummaryInstructions(meetingType: MeetingRecapType): string {
  const instructions: Record<MeetingRecapType, string[]> = {
    weekly_spqrc: [
      "For weekly_spqrc, prefer meetingNotes headings like these when supported by the transcript:",
      "Executive Summary",
      "Safety, People, Quality, Delivery, and Cost Updates",
      "Plant Operations Reports",
      "Customer or Sales Updates",
      "Compliance or Program Updates",
      "Decisions and Announcements",
      "Risks and Blockers",
      "Open Questions"
    ],
    weekly_sales: [
      "For weekly_sales, prefer meetingNotes headings like these when supported by the transcript:",
      "1. Weekly Summary",
      "2. Key Wins and Progress",
      "3. Sales Pipeline and Customer Follow-Up",
      "4. Staffing and Operations",
      "5. Revenue, Forecast, and Reporting",
      "6. CRM and Tracking",
      "7. Pricing and Contract Discussion",
      "8. Decisions Made",
      "9. Action Items",
      "10. Risks and Blockers",
      "11. Open Questions",
      "For weekly_sales, include Meeting, Date, Weekly focus, and a note about cleaned speaker labels when that context is available.",
      "For weekly_sales, use Action Items for concrete follow-up work with owner and due timing. Keep followUpTasks and actionItems aligned with that section."
    ],
    plant_meeting: [
      "For plant_meeting, prefer meetingNotes headings like these when supported by the transcript:",
      "Executive Summary",
      "Plant Operations and Safety Reports",
      "Production, Schedule, and Customer Updates",
      "Quality and Customer Issues",
      "Maintenance, Equipment, and Material Constraints",
      "Staffing and Operational Updates",
      "Cost, Productivity, and Efficiency",
      "Decisions",
      "Risks and Blockers",
      "Open Questions"
    ],
    general: [
      "For general, prefer meetingNotes headings like these when supported by the transcript:",
      "Executive Summary",
      "Key Discussion Topics",
      "Project or Business Updates",
      "Operational Updates",
      "Customer or Stakeholder Updates",
      "Decisions",
      "Risks and Blockers",
      "Open Questions"
    ]
  };
  return [`Summary template label: ${meetingRecapTypeLabels[meetingType]}`, ...instructions[meetingType], "Only include headings that are supported by the transcript."].join("\n");
}
