import { meetingRecapTypeLabels, type MeetingRecapType } from "./meetingTypes";
import type { SummaryInput } from "./types";

export function buildSummaryPrompt(input: SummaryInput): string {
  const meetingType = input.meetingType ?? "general";
  const recapDepth = input.recapDepth ?? "standard";
  return [
    buildBaseInstructions(input.prompt),
    `Meeting: ${input.meetingSubject}`,
    input.meetingStartTime ? `Start time: ${input.meetingStartTime}` : "",
    input.meetingEndTime ? `End time: ${input.meetingEndTime}` : "",
    input.meetingDurationMinutes !== undefined ? `Meeting duration minutes: ${input.meetingDurationMinutes}` : "",
    input.transcriptDurationMinutes !== undefined ? `Transcript duration minutes: ${input.transcriptDurationMinutes}` : "",
    input.speakerTurnCount !== undefined ? `Speaker turn count: ${input.speakerTurnCount}` : "",
    input.wordCount !== undefined ? `Word count: ${input.wordCount}` : "",
    input.organizerEmail ? `Organizer: ${input.organizerEmail}` : "",
    `Attendees: ${input.attendees.map((attendee) => attendee.name ? `${attendee.name} <${attendee.email}>` : attendee.email).join(", ")}`,
    `Resolved meeting type: ${meetingType}`,
    `Resolved recap depth: ${recapDepth}`,
    buildRecapDepthInstructions(recapDepth, meetingType),
    "JSON shape: {\"meetingType\":\"weekly_spqrc\"|\"weekly_sales\"|\"plant_meeting\"|\"general\",\"recapDepth\":\"brief\"|\"standard\",\"executiveRecap\":{\"topPriorities\":[{\"title\":\"string\",\"summary\":\"string\",\"whyItMatters\":\"string\",\"owner\":\"string\",\"nextStep\":\"string\",\"dueDate\":\"string\"}],\"immediateActions\":[{\"priority\":\"string\",\"action\":\"string\",\"owner\":\"string\",\"due\":\"string\",\"relatedCustomerOrArea\":\"string\",\"status\":\"string\"}],\"keyDecisions\":[{\"decision\":\"string\",\"impact\":\"string\",\"ownerOrFollowUp\":\"string\"}],\"majorRisks\":[{\"title\":\"string\",\"explanation\":\"string\",\"impact\":\"string\",\"mitigationOrNextStep\":\"string\"}],\"detailedRecap\":[{\"heading\":\"string\",\"summary\":\"string\"}],\"winsAndProgress\":[{\"title\":\"string\",\"detail\":\"string\",\"impact\":\"string\"}],\"fullActionRegister\":[{\"action\":\"string\",\"owner\":\"string\",\"due\":\"string\",\"priority\":\"High\"|\"Medium\"|\"Low\",\"relatedArea\":\"string\",\"notes\":\"string\"}],\"openQuestions\":[{\"question\":\"string\",\"whyItMatters\":\"string\",\"ownerOrBestNextStep\":\"string\"}],\"referenceNotes\":[{\"topic\":\"string\",\"notes\":[\"string\"]}]},\"meetingNotes\":[{\"heading\":\"string\",\"overview\":\"string\",\"items\":[{\"title\":\"string\",\"detail\":\"string\"}]}],\"followUpTasks\":[{\"title\":\"string\",\"description\":\"string\",\"owners\":[\"string\"],\"dueDate\":\"string\"}],\"summary\":string[],\"decisions\":string[],\"actionItems\":[{\"owner\":\"string\",\"task\":\"string\",\"dueDate\":\"string\"}],\"openQuestions\":string[],\"risks\":string[],\"followUps\":string[]}",
    "Transcript:",
    input.transcriptText
  ]
    .filter(Boolean)
    .join("\n");
}

function buildBaseInstructions(customPrompt?: string): string {
  return [
    customPrompt,
    "You are generating a WGS / MinutesBot meeting recap in a polished business format.",
    "First respect the provided recapDepth.",
    "The renderer displays this disclaimer at the top: Generated by AI. Be sure to check for accuracy. Do not include this disclaimer in any JSON field.",
    "Return strict JSON only.",
    "Match the existing application JSON schema exactly.",
    "Return strict JSON only using the required schema.",
    "Do not return markdown outside JSON, code fences, prose, comments, explanatory text, or extra keys.",
    "Do not invent facts, owners, due dates, decisions, risks, metrics, customer names, plant names, or follow-ups.",
    "If something is unclear, say \"Unclear\".",
    "If something is not mentioned, say \"Not specified\".",
    "If there are no items for a field, return an empty array.",
    "If owner is not specified, use owner \"Unassigned\".",
    "If due date is not specified, use dueDate \"TBD\".",
    "Convert relative due dates using the meeting date when possible. Example: \"tomorrow\" from a 2026-06-01 meeting becomes \"2026-06-02\".",
    "Use the resolved meeting type provided by the classifier.",
    "Use the resolved meeting type supplied by the classifier.",
    "Do not reclassify the meeting during recap generation.",
    "Use the resolved recap depth provided by the classifier.",
    "Do not change recapDepth during recap generation.",
    "Preserve important names, locations, customers, plants, systems, deadlines, and metrics when stated.",
    "Be concise and action-oriented.",
    "Prioritize what changed, what was decided, who owns what, and what must happen next.",
    "Avoid verbatim quotes unless the exact wording is critical.",
    "Use plain business language suitable for an email recap.",
    "For recapDepth brief, generate a concise recap for a very short meeting. Do not create a full topic-grouped recap. Do not infer a large agenda from minimal content. Include only what was actually captured. Clearly state when no substantive content, decisions, or follow-up tasks were captured. Keep the recap short. Do not pad short meetings.",
    "For recapDepth standard, generate one unified executive recap. Do not organize by transcript chunk. Do not emit repeated Weekly Summary sections.",
    "For standard recaps, model this structure in executiveRecap:",
    "# {Meeting Name} — Executive Recap",
    "{Meeting Date / Time}",
    "AI-generated recap. Review for accuracy.",
    "The recap must follow this reading order inside the applicable JSON fields: 1. At a Glance, 2. Detailed Recap, 3. Full Action Register, 4. Open Questions, 5. Reference Notes.",
    "## 1. At a Glance",
    "At a Glance section must appear first and must contain the highest-value information only.",
    "Include Top Priorities, Immediate Actions, Key Decisions, and Major Risks / Blockers.",
    "### Top Priorities",
    "List 5 to 7 maximum. Rank by business importance, not transcript order.",
    "Each priority must include: title, concise summary, why it matters, owner or next step when known, and due date when known.",
    "Do not include low-value meeting context or general discussion in Top Priorities.",
    "Priority ranking order: 1. Customer-impacting blockers or urgent customer work; 2. Revenue, payment, collections, quote activity, sales pipeline movement, or demand changes; 3. Staffing shortages, absenteeism, hiring, labor availability, or capacity constraints; 4. Decisions, approvals, rejected options, committed plans, or direction changes; 5. Operational readiness issues involving tools, job numbers, work instructions, reporting, transportation, facility setup, equipment, materials, or dependencies; 6. Open questions that block execution; 7. Important risks that need leadership visibility.",
    "### Immediate Actions",
    "Include the most urgent action items first and use no more than 10 immediate actions.",
    "Prioritize customer-facing, revenue-related, delivery-risk, staffing-risk, and blocker-removal actions.",
    "Use this table shape: | Priority | Action | Owner | Due | Related Customer / Area | Status |.",
    "Start each task with a verb.",
    "Do not create action items from vague discussion unless there is a clear requested follow-up, owner, committed next step, or deadline.",
    "### Key Decisions",
    "Include only confirmed decisions, agreements, approvals, rejected options, committed plans, or direction changes.",
    "Do not include discussion points, ideas, possibilities, or unresolved options as decisions.",
    "If no clear decisions were confirmed, leave executiveRecap.keyDecisions empty and put No clear decisions were confirmed in the transcript in decisions only if useful for legacy compatibility.",
    "### Major Risks / Blockers",
    "Capture blockers, delays, safety, quality, delivery, cost, customer, revenue, staffing, equipment, material, documentation, reporting, and dependency risks.",
    "List the most important risks with title, explanation, likely impact, and mitigationOrNextStep.",
    "Use \"Not defined\" when no mitigation was discussed.",
    "## 2. Detailed Recap",
    "Organize detailedRecap by business topic, not transcript order. Use only relevant sections from Customer Work & Sales Pipeline, Staffing, Capacity & Operations, Reporting, CRM & Tracking, Documentation & Process Control, Financial / Pricing / Contract Items, and Wins & Progress.",
    "For Weekly Sales meetings, Customer Work & Sales Pipeline captures active customer jobs, customer follow-ups, opportunities, prospecting, quote activity, demand changes, customer response delays, payment issues, and collections issues.",
    "For Weekly Sales meetings, Staffing, Capacity & Operations captures staffing levels, absenteeism, hiring, headcount needs, manpower gaps, schedule coverage, plant support, tools, transportation, facility setup, storage needs, operational readiness, and execution blockers.",
    "For Weekly Sales meetings, Reporting, CRM & Tracking captures CRM updates, reporting gaps, tracking tools, spreadsheet requests, forecast visibility, plant-level reporting, month-end close issues, missing data, and data validation needs.",
    "For Weekly Sales meetings, Documentation & Process Control captures work instructions, missing documents, repositories, template standardization, customer paperwork, purchase orders, shared-drive issues, OneDrive issues, and process-control gaps.",
    "For Weekly Sales meetings, Financial / Pricing / Contract Items captures pricing approach, billing method, tooling cost treatment, contract issues, collections concerns, revenue impact, payment follow-up, sales totals, plant goal attainment, and forecast implications. Only include this section when discussed.",
    "For Weekly Sales meetings, Wins & Progress includes only meaningful wins or progress that affect customers, revenue, staffing, delivery, process control, or operating readiness.",
    "## 3. Full Action Register",
    "Populate fullActionRegister with the complete deduplicated task list. Each item must include owner, task, dueDate, priority, related area/customer when known, and notes when useful.",
    "Priority values must be High, Medium, or Low.",
    "Priority definitions: High is customer-impacting, revenue-impacting, delivery-blocking, staffing-critical, deadline-sensitive, or needed to unblock other work. Medium is important operational, reporting, documentation, or customer follow-up work without immediate delivery or revenue impact. Low is useful follow-up, background cleanup, non-urgent documentation, or longer-term improvement.",
    "Preserve all concrete actions from the transcript. Combine split tasks when they clearly refer to the same work. Use \"Unassigned\" and \"TBD\" when needed.",
    "## 4. Open Questions",
    "Populate executiveRecap.openQuestions only with unresolved items that affect execution, customer communication, staffing, revenue, reporting, or accountability.",
    "Capture unresolved questions, missing information, unclear ownership, unclear deadlines, pending customer answers, pending plant data, uncertain job details, unclear customer locations, unclear staffing numbers, unresolved payment status, and unresolved reporting requirements.",
    "Merge overlapping questions. Prefer 5 to 12 focused open questions maximum unless the transcript clearly contains more important unresolved items.",
    "## 5. Reference Notes",
    "Use referenceNotes for lower-priority traceability details grouped by topic. Keep notes brief.",
    "Do not repeat the At a Glance section in Reference Notes. Include speaker names only when clearly supported.",
    "For standard recaps, also populate meetingNotes for backward compatibility using at most these headings when supported: 1. At a Glance:, 2. Detailed Recap:, 5. Reference Notes:. Do not duplicate the same detail across meetingNotes items.",
    "For standard recaps, each meetingNotes heading should end with a colon. Each subtopic title should be concise and each detail should be 1 to 2 sentences.",
    "Clean up unclear speaker labels such as \"Conference Room Computer\". Attribute to a named speaker only when the transcript supports it; otherwise write without that speaker label.",
    "If a one-word weekly focus is stated, include it in the summary and preserve the exact word.",
    "Action items must be concrete and execution-focused. Each action item must include owner, task, and dueDate. Use owner \"Unassigned\" and dueDate \"TBD\" when not specified.",
    "followUpTasks must mirror the Teams format. Each follow-up task must include title, description, owners, and dueDate. Use owners [\"Unassigned\"] and dueDate \"TBD\" when not specified.",
    "Do not create a follow-up task unless the transcript supports it.",
    "Populate actionItems with one action item for each followUpTasks item when appropriate. Use owner as comma-separated owners or \"Unassigned\", task as the same core task as followUpTasks.description, and dueDate as the same dueDate.",
    "Merge duplicate action items.",
    "Deduplicate similar actions, risks, decisions, open questions, follow-ups, priorities, and reference notes across transcript chunks.",
    "Populate summary with 4 to 8 concise executive bullets for compatibility. Capture top priorities, key business impacts, major risks, revenue or operating impact, and any stated one-word weekly focus.",
    "Capture action items related to safety follow-up, quality issue closure, delivery or customer response, cost reduction, sales or customer follow-up, quote or pricing work, plant operational improvements, open issues, and data or reporting needed before the next meeting.",
    "Do not convert general discussion into action items unless an action was clearly assigned or strongly implied.",
    "Only include confirmed decisions, agreements, approvals, rejected options, committed plans, or direction changes. Do not treat discussion as a decision unless there was clear agreement.",
    "Risks must capture blockers, delays, safety risks, quality risks, delivery risks, cost risks, customer or revenue risks, staffing risks, equipment or material constraints, and dependencies.",
    "Open questions must capture unresolved questions, missing information, unclear ownership, unclear deadlines, pending customer answers, pending plant data, or unanswered operational concerns.",
    "Follow-ups must capture planned future meetings, customer follow-ups, plant check-ins, internal reviews, reports to prepare, data to validate, or topics to revisit in the next weekly meeting.",
    "For Weekly Sales meetings, emphasize customer blockers, revenue movement, collections and payment follow-up, quote activity, new opportunities, customer demand changes, staffing and capacity risks, job setup requirements, forecast, sales, CRM, and reporting cleanup, decisions, risks, action items, and open questions.",
    "For Weekly SPQRC meetings, emphasize Safety, People, Quality, Responsiveness / delivery, Cost, plant updates, decisions, risks, and actions.",
    "For Individual Plant Meetings, emphasize plant operations, schedule, safety, quality, staffing, constraints, equipment, materials, customer needs, and actions.",
    "For General meetings, use a concise business recap structure: At a Glance, Key Discussion Points, Decisions, Actions, Risks, Open Questions, and Reference Notes.",
    "Quality check before returning JSON: the most important business items appear first; the recap does not start with generic meeting context unless no substantive content exists; action items are deduplicated; decisions are separated from action items; risks are separated from open questions; repeated transcript chunks are merged; unclear information is marked clearly instead of guessed; no unsupported owner, deadline, metric, customer, plant, or decision is invented."
  ]
    .filter(Boolean)
    .join("\n");
}

function buildRecapDepthInstructions(recapDepth: NonNullable<SummaryInput["recapDepth"]>, meetingType: MeetingRecapType): string {
  if (recapDepth === "brief") {
    return [
      "recapDepth is brief.",
      "Generate a simplified short-meeting recap using the resolved meeting type only as context.",
      "Do not use the full standard template structure.",
      "Do not create fake sections like Safety, Sales, Plant, Cost, or Quality unless the short meeting actually discussed them.",
      "meetingNotes must contain exactly 1 heading: Brief meeting recap.",
      "meetingNotes[0].items must contain at most 2 items titled What happened and Outcome.",
      "summary must contain 1 to 3 bullets.",
      "followUpTasks must contain only real tasks supported by the transcript.",
      "decisions must contain only confirmed decisions.",
      "risks should usually be empty unless a real risk was stated.",
      "openQuestions should include transcript limitations if relevant.",
      "If the transcript is mostly empty, joining chatter, bot setup, or low quality, say so clearly instead of inventing notes.",
      "For a short meeting with a real decision or assigned action, keep recapDepth brief and include that decision or action clearly."
    ].join("\n");
  }
  return [
    "recapDepth is standard.",
    "Generate one executive recap with At a Glance first, detailed business-topic context second, then the full action register, open questions, and reference notes.",
    buildMeetingTypeSummaryInstructions(meetingType)
  ].join("\n");
}

export function buildMeetingTypeSummaryInstructions(meetingType: MeetingRecapType): string {
  const instructions: Record<MeetingRecapType, string[]> = {
    weekly_spqrc: [
      "For weekly_spqrc, prefer meetingNotes headings like these when supported by the transcript:",
      "Executive Summary",
      "Safety, People, Quality, Delivery, and Cost Updates",
      "Plant Operations Reports",
      "Customer or Sales Updates",
      "Compliance or Program Updates",
      "Decisions and Announcements",
      "Risks and Blockers",
      "Open Questions"
    ],
    weekly_sales: [
      "For weekly_sales, prioritize customer follow-ups, quote movement, revenue or collections, pipeline health, CRM/reporting gaps, staffing or capacity constraints, pricing or contract concerns, decisions, risks, and open execution questions.",
      "For weekly_sales, executiveRecap.detailedRecap should use business-topic headings such as Customer Work & Sales Pipeline, Staffing, Capacity & Operations, Reporting, CRM & Tracking, Documentation & Process Control, Financial / Pricing / Contract Items, and Wins & Progress when supported.",
      "For weekly_sales, keep followUpTasks, actionItems, immediateActions, and fullActionRegister aligned without duplicates."
    ],
    plant_meeting: [
      "For plant_meeting, prefer meetingNotes headings like these when supported by the transcript:",
      "Executive Summary",
      "Plant Operations and Safety Reports",
      "Production, Schedule, and Customer Updates",
      "Quality and Customer Issues",
      "Maintenance, Equipment, and Material Constraints",
      "Staffing and Operational Updates",
      "Cost, Productivity, and Efficiency",
      "Decisions",
      "Risks and Blockers",
      "Open Questions"
    ],
    general: [
      "For general, prefer meetingNotes headings like these when supported by the transcript:",
      "Executive Summary",
      "Key Discussion Topics",
      "Project or Business Updates",
      "Operational Updates",
      "Customer or Stakeholder Updates",
      "Decisions",
      "Risks and Blockers",
      "Open Questions"
    ]
  };
  return [`Summary template label: ${meetingRecapTypeLabels[meetingType]}`, ...instructions[meetingType], "Only include headings that are supported by the transcript."].join("\n");
}
