import type { RecapDocument } from "@minutesbot/summary-engine";
import type { RecapEmailInput, RenderedEmail } from "./types";

const disclaimer = "Generated by AI from the meeting recording. Check important details for accuracy.";

export function renderRecapEmail(input: RecapEmailInput): RenderedEmail {
  const subjectPrefix = (input.subjectPrefix ?? "Meeting recap").trim();
  const subject = sanitizeSubject(`${subjectPrefix}: ${input.subject}`);
  const when = formatWhen(input.startTime, input.timeZone);
  return {
    subject,
    text: renderText(input, when),
    html: renderHtml(input, when)
  };
}

function renderText(input: RecapEmailInput, when: string | null): string {
  const { recap } = input;
  const lines: string[] = [];
  lines.push(input.subject);
  if (when) lines.push(when);
  lines.push("", disclaimer, "");
  if (input.introText?.trim()) lines.push(input.introText.trim(), "");
  lines.push("Overview", "--------", recap.overview, "");
  pushTextSection(lines, "Decisions", recap.decisions);
  if (recap.actionItems.length > 0) {
    lines.push("Action items", "------------");
    for (const item of recap.actionItems) {
      const parts = [item.task];
      if (item.owner) parts.push(`owner: ${item.owner}`);
      if (item.dueDate) parts.push(`due: ${item.dueDate}`);
      lines.push(`- ${parts.join(" — ")}`);
    }
    lines.push("");
  }
  pushTextSection(lines, "Risks and blockers", recap.risks);
  pushTextSection(lines, "Open questions", recap.openQuestions);
  if (recap.importantDates.length > 0) {
    lines.push("Important dates", "---------------");
    for (const entry of recap.importantDates) lines.push(`- ${entry.date}: ${entry.description}`);
    lines.push("");
  }
  pushTextSection(lines, "Follow-ups", recap.followUps);
  if (input.excludedRecipients && input.excludedRecipients.length > 0) {
    lines.push(`Not delivered to (outside allowed domains): ${input.excludedRecipients.join(", ")}`, "");
  }
  if (input.adminUrl) lines.push(`Details and artifacts: ${input.adminUrl}`);
  return lines.join("\n").trimEnd() + "\n";
}

function pushTextSection(lines: string[], title: string, items: string[]): void {
  if (items.length === 0) return;
  lines.push(title, "-".repeat(title.length));
  for (const item of items) lines.push(`- ${item}`);
  lines.push("");
}

function renderHtml(input: RecapEmailInput, when: string | null): string {
  const { recap } = input;
  const sections: string[] = [];
  sections.push(`<h1 style="font-size:18px;margin:0 0 4px">${escapeHtml(input.subject)}</h1>`);
  if (when) sections.push(`<p style="color:#555;margin:0 0 12px">${escapeHtml(when)}</p>`);
  sections.push(`<p style="color:#777;font-size:12px;margin:0 0 16px">${escapeHtml(disclaimer)}</p>`);
  if (input.introText?.trim()) sections.push(`<p>${escapeHtml(input.introText.trim())}</p>`);
  sections.push(htmlSection("Overview", `<p>${escapeHtml(recap.overview)}</p>`));
  sections.push(htmlList("Decisions", recap.decisions));
  if (recap.actionItems.length > 0) {
    const items = recap.actionItems
      .map((item) => {
        const meta = [item.owner ? `owner: ${item.owner}` : null, item.dueDate ? `due: ${item.dueDate}` : null]
          .filter(Boolean)
          .join(", ");
        return `<li>${escapeHtml(item.task)}${meta ? ` <span style="color:#555">(${escapeHtml(meta)})</span>` : ""}</li>`;
      })
      .join("");
    sections.push(htmlSection("Action items", `<ul>${items}</ul>`));
  }
  sections.push(htmlList("Risks and blockers", recap.risks));
  sections.push(htmlList("Open questions", recap.openQuestions));
  if (recap.importantDates.length > 0) {
    const items = recap.importantDates
      .map((entry) => `<li><strong>${escapeHtml(entry.date)}</strong>: ${escapeHtml(entry.description)}</li>`)
      .join("");
    sections.push(htmlSection("Important dates", `<ul>${items}</ul>`));
  }
  sections.push(htmlList("Follow-ups", recap.followUps));
  if (input.excludedRecipients && input.excludedRecipients.length > 0) {
    sections.push(
      `<p style="color:#777;font-size:12px">Not delivered to (outside allowed domains): ${input.excludedRecipients.map(escapeHtml).join(", ")}</p>`
    );
  }
  if (input.adminUrl) {
    sections.push(`<p><a href="${escapeAttribute(input.adminUrl)}">Details and artifacts</a></p>`);
  }
  return [
    '<!doctype html><html><body style="font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#1a1a1a;max-width:640px;margin:0 auto;padding:16px">',
    sections.filter(Boolean).join("\n"),
    "</body></html>"
  ].join("\n");
}

function htmlSection(title: string, body: string): string {
  return `<h2 style="font-size:15px;margin:18px 0 6px">${escapeHtml(title)}</h2>${body}`;
}

function htmlList(title: string, items: string[]): string {
  if (items.length === 0) return "";
  return htmlSection(title, `<ul>${items.map((item) => `<li>${escapeHtml(item)}</li>`).join("")}</ul>`);
}

function formatWhen(startTime?: string, timeZone?: string): string | null {
  if (!startTime) return null;
  const date = new Date(startTime);
  if (Number.isNaN(date.getTime())) return null;
  try {
    return new Intl.DateTimeFormat("en", {
      dateStyle: "full",
      timeStyle: "short",
      timeZone: timeZone || "UTC"
    }).format(date);
  } catch {
    return new Intl.DateTimeFormat("en", { dateStyle: "full", timeStyle: "short", timeZone: "UTC" }).format(date);
  }
}

function sanitizeSubject(subject: string): string {
  return subject.replace(/[\r\n\0]+/g, " ").trim().slice(0, 255);
}

export function escapeHtml(value: string): string {
  return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#39;");
}

function escapeAttribute(value: string): string {
  return escapeHtml(value);
}

export type { RecapDocument };
