import { meetingRecapTypeLabels } from "@minutesbot/summary-engine";
import { cleanMeetingSubject } from "@minutesbot/shared";
import type { RenderedEmail, SummaryEmailInput, SummaryEmailSummary } from "./types";

type ExecutiveRecap = NonNullable<SummaryEmailSummary["executiveRecap"]>;

const aiDisclaimer = "Generated by AI. Be sure to check for accuracy.";
const footerSenderText = "Sent by wgsbot a fork of minutesbot";
const footerReviewText = "This recap was generated by AI from the meeting transcript and may require human review.";
const defaultTranscriptDownloadExpirationHours = 24;

export function renderSummaryEmail(input: SummaryEmailInput): RenderedEmail {
  const summary = normalizeSummary(input.summary);
  const renderInput = { ...input, subject: cleanMeetingSubject(input.subject) || input.subject.trim() || "Untitled meeting" };
  const meetingTypeLabel = meetingRecapTypeLabels[summary.meetingType];
  const recapDepthLabel = summary.recapDepth === "brief" ? "Brief" : "Standard";
  const text = renderText({ ...renderInput, summary }, meetingTypeLabel, recapDepthLabel);
  const html = renderHtml({ ...renderInput, summary }, meetingTypeLabel, recapDepthLabel);
  return { subject: `${input.recap?.subjectPrefix ?? "Meeting summary"}: ${renderInput.subject}`, text, html };
}

function normalizeSummary(summary: SummaryEmailSummary): Required<Pick<SummaryEmailSummary, "meetingType" | "recapDepth" | "executiveRecap" | "meetingNotes" | "followUpTasks">> & SummaryEmailSummary {
  return {
    ...summary,
    meetingType: summary.meetingType ?? "general",
    recapDepth: summary.recapDepth ?? "standard",
    executiveRecap: summary.executiveRecap ?? emptyExecutiveRecap(),
    meetingNotes: summary.meetingNotes ?? [],
    followUpTasks: summary.followUpTasks ?? []
  };
}

function renderText(input: SummaryEmailInput & { summary: ReturnType<typeof normalizeSummary> }, meetingTypeLabel: string, recapDepthLabel: string): string {
  const secondarySections = resolveSecondarySections(input, isLegacyOnly(input.summary));
  const displayDate = input.date ? formatMeetingDate(input.date) : "";
  const hasExecutive = hasExecutiveRecap(input.summary.executiveRecap);
  return [
    aiDisclaimer,
    "",
    "Meeting recap",
    `Subject: ${input.subject}`,
    displayDate ? `Date: ${displayDate}` : "",
    `Meeting type: ${meetingTypeLabel}`,
    `Recap depth: ${recapDepthLabel}`,
    input.transcriptDownloadUrl ? `Download Transcript: ${input.transcriptDownloadUrl}` : "",
    input.transcriptDownloadUrl ? transcriptExpirationText(input.transcriptDownloadExpirationHours) : "",
    input.recap?.introText ?? "",
    input.summary.recapDepth === "brief" ? "Brief meeting detected. This recap is simplified because the meeting or captured transcript was very short." : "",
    "",
    ...(hasExecutive
      ? renderExecutiveRecapText(input, meetingTypeLabel)
      : [
          "Meeting notes:",
          "",
          ...renderMeetingNotesText(input.summary.meetingNotes),
          "Follow-up tasks:",
          "",
          ...renderFollowUpTasksText(input.summary.followUpTasks),
          ...secondarySections.map((section) => sectionText(section.label, section.items))
        ]),
    sectionText("Not sent to external attendees", input.excludedRecipients ?? [])
  ]
    .filter(Boolean)
    .join("\n");
}

function renderHtml(input: SummaryEmailInput & { summary: ReturnType<typeof normalizeSummary> }, meetingTypeLabel: string, recapDepthLabel: string): string {
  const secondarySections = resolveSecondarySections(input, isLegacyOnly(input.summary));
  const hasExecutive = hasExecutiveRecap(input.summary.executiveRecap);
  return [
    '<meta name="color-scheme" content="light only">',
    '<meta name="supported-color-schemes" content="light">',
    "<style>:root { color-scheme: only light; supported-color-schemes: light; }</style>",
    '<div style="margin:0;padding:0 8px 18px;background:#ffffff;background-color:#ffffff;font-family:Inter,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#111827;color-scheme:only light;">',
    '<div style="max-width:760px;margin:0 auto;background:#ffffff;background-color:#ffffff;border:1px solid #c4b5fd;border-radius:10px;overflow:hidden;color:#111827;">',
    '<div style="height:4px;background:#5b21b6;background-color:#5b21b6;"></div>',
    '<div style="padding:14px 20px 20px;background:#ffffff;background-color:#ffffff;color:#111827;">',
    renderHeader(input, meetingTypeLabel),
    callout(aiDisclaimer),
    input.summary.recapDepth === "brief" ? callout("Brief meeting detected<br><span style=\"font-weight:650;\">This recap is simplified because the meeting or captured transcript was very short.</span>", "#eef2ff", "#4338ca", "#312e81") : "",
    input.recap?.introText ? paragraph(input.recap.introText, "margin:15px 0 0;font-size:15px;line-height:1.55;color:#374151;") : "",
    hasExecutive
      ? renderExecutiveRecapHtml(input, meetingTypeLabel)
      : [
          sectionHeading("Meeting notes"),
          renderMeetingNotesHtml(input.summary.meetingNotes),
          sectionHeading("Follow-up tasks"),
          renderFollowUpTasksHtml(input.summary.followUpTasks),
          secondarySections.map((section) => renderBulletSection(section.label, section.items)).join("")
        ].join(""),
    input.excludedRecipients?.length ? renderBulletSection("Not sent to external attendees", input.excludedRecipients) : "",
    `<div style="margin-top:22px;padding-top:13px;border-top:1px solid #c4b5fd;color:#374151;font-size:13px;line-height:1.5;">${footerSenderText}<br>${footerReviewText}</div>`,
    "</div></div></div>"
  ].join("");
}

function renderHeader(input: SummaryEmailInput & { summary: ReturnType<typeof normalizeSummary> }, meetingTypeLabel: string): string {
  const displayDate = input.date ? formatMeetingDate(input.date) : "";
  return [
    '<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border-collapse:collapse;width:100%;margin:0 0 4px;">',
    "<tr>",
    '<td valign="top" style="padding:0 16px 0 0;">',
    '<div style="font-size:13px;letter-spacing:.08em;text-transform:uppercase;color:#5b21b6;font-weight:800;">WGS / minutesbot</div>',
    '<h1 style="margin:6px 0 5px;font-size:27px;line-height:1.18;color:#111827;">Meeting recap</h1>',
    paragraph(input.subject, "margin:0;font-size:18px;line-height:1.4;color:#111827;font-weight:800;"),
    "</td>",
    '<td valign="top" align="right" style="padding:2px 0 0 16px;text-align:right;">',
    displayDate ? paragraph(displayDate, "margin:0 0 9px;font-size:15px;line-height:1.4;color:#374151;") : "",
    `<div style="display:block;margin:0;">${badge(meetingTypeLabel)}${input.summary.recapDepth === "brief" ? badge("Brief recap", "#eef2ff", "#312e81") : ""}</div>`,
    input.transcriptDownloadUrl
      ? `<p style="margin:6px 0 0;font-size:15px;line-height:1.4;"><a href="${escapeAttribute(input.transcriptDownloadUrl)}" style="color:#5b21b6;font-weight:800;text-decoration:underline;">Download Transcript</a></p>` +
        paragraph(transcriptExpirationText(input.transcriptDownloadExpirationHours), "margin:2px 0 0;font-size:13px;line-height:1.4;color:#4b5563;")
      : "",
    "</td>",
    "</tr>",
    "</table>"
  ].join("");
}

function renderMeetingNotesText(notes: ReturnType<typeof normalizeSummary>["meetingNotes"]): string[] {
  if (notes.length === 0) return ["None captured.", ""];
  return notes.flatMap((note) => {
    const overview = shouldRenderMeetingNoteOverview(note.overview) ? note.overview : "";
    return [
      note.heading,
      overview,
      ...note.items.flatMap((item) => [item.title, item.detail, ""]),
      ""
    ];
  });
}

function renderFollowUpTasksText(tasks: ReturnType<typeof normalizeSummary>["followUpTasks"]): string[] {
  if (tasks.length === 0) return ["No follow-up tasks captured.", ""];
  return tasks.flatMap((task) => [
    task.title,
    task.description,
    `Owner: ${formatOwners(task.owners)}`,
    `Due: ${task.dueDate}`,
    ""
  ]);
}

function renderMeetingNotesHtml(notes: ReturnType<typeof normalizeSummary>["meetingNotes"]): string {
  if (notes.length === 0) return paragraph("None captured.", "margin:0 0 12px;font-size:15px;line-height:1.55;color:#374151;");
  return notes
    .map(
      (note) =>
        `<div style="margin:0 0 14px;padding:0 0 14px;border-bottom:1px solid #ede9fe;">` +
        `<h3 style="margin:0 0 7px;font-size:17px;line-height:1.35;color:#111827;">${escapeHtml(note.heading)}</h3>` +
        (shouldRenderMeetingNoteOverview(note.overview) ? paragraph(note.overview, "margin:0 0 11px;font-size:15px;line-height:1.55;color:#374151;") : "") +
        note.items
          .map((item) => `<p style="margin:9px 0 4px;font-size:15px;line-height:1.45;color:#111827;"><strong style="color:#111827;">${escapeHtml(item.title)}</strong></p>${paragraph(item.detail, "margin:0;font-size:15px;line-height:1.55;color:#374151;")}`)
          .join("") +
        "</div>"
    )
    .join("");
}

function shouldRenderMeetingNoteOverview(value: string): boolean {
  return value.trim() !== "" && value.trim() !== aiDisclaimer;
}

function renderFollowUpTasksHtml(tasks: ReturnType<typeof normalizeSummary>["followUpTasks"]): string {
  if (tasks.length === 0) return paragraph("No follow-up tasks captured.", "margin:0 0 12px;font-size:15px;line-height:1.55;color:#374151;");
  return tasks
    .map(
      (task) =>
        `<div style="margin:0 0 12px;padding:11px 12px 11px 13px;border-left:4px solid #5b21b6;border-top:1px solid #ddd6fe;border-right:1px solid #ddd6fe;border-bottom:1px solid #ddd6fe;background:#ffffff;background-color:#ffffff;color:#111827;">` +
        `<p style="margin:0 0 5px;font-size:15px;line-height:1.45;color:#111827;"><strong style="color:#111827;">${escapeHtml(task.title)}</strong></p>` +
        paragraph(task.description, "margin:0 0 7px;font-size:15px;line-height:1.55;color:#374151;") +
        paragraph(`Owner: ${formatOwners(task.owners)}`, "margin:0 0 3px;font-size:13px;line-height:1.45;color:#4b5563;") +
        paragraph(`Due: ${task.dueDate}`, "margin:0;font-size:13px;line-height:1.45;color:#4b5563;") +
        "</div>"
    )
    .join("");
}

function renderExecutiveRecapText(input: SummaryEmailInput & { summary: ReturnType<typeof normalizeSummary> }, meetingTypeLabel: string): string[] {
  const recap = input.summary.executiveRecap;
  const personSpecificBriefs = notesByHeading(input.summary.meetingNotes, "Person-Specific Briefs:");
  const noteGroups = notesByHeading(input.summary.meetingNotes, "Notes:");
  return [
    "1. Executive Highlights",
    "",
    ...(recap.topPriorities.length
      ? recap.topPriorities.flatMap((item) => [
          `- **${item.title}** — ${item.summary}`,
          `  **Impact:** ${item.whyItMatters}`,
          `  **Owner / next step:** ${item.owner || "Unassigned"}. ${item.nextStep || "Due TBD"} ${item.dueDate || ""}`.trim(),
          ""
        ])
      : ["None captured.", ""]),
    "2. Person-Specific Briefs",
    ...renderMeetingNotesText(personSpecificBriefs),
    "3. Notes",
    ...(recap.detailedRecap.length ? recap.detailedRecap.flatMap((item) => [`${item.heading}`, item.summary, ""]) : []),
    ...renderMeetingNotesText(noteGroups),
    ...(recap.winsAndProgress.length
      ? [
          "Wins & Progress",
          ...recap.winsAndProgress.flatMap((item) => [`- **${item.title}** — ${item.detail}. **Impact:** ${item.impact}.`]),
          ""
        ]
      : []),
    ...(recap.detailedRecap.length === 0 && noteGroups.length === 0 && recap.winsAndProgress.length === 0 ? ["No detailed business topics captured.", ""] : []),
    "4. Action Items",
    "Immediate Actions",
    ...renderTextTable(
      ["Priority", "Action", "Owner", "Due", "Related Customer / Area", "Status"],
      recap.immediateActions.map((item) => [item.priority, item.action, item.owner, item.due, item.relatedCustomerOrArea, item.status])
    ),
    "",
    "Full Action Register",
    ...renderTextTable(
      ["#", "Action", "Owner", "Due", "Priority", "Related Area", "Notes"],
      recap.fullActionRegister.map((item, index) => [String(index + 1), item.action, item.owner, item.due, item.priority, item.relatedArea, item.notes])
    ),
    "",
    "5. Decisions",
    ...(recap.keyDecisions.length
      ? recap.keyDecisions.flatMap((item) => [
          `- **Decision:** ${item.decision}`,
          `  **Impact:** ${item.impact}`,
          `  **Owner / follow-up:** ${item.ownerOrFollowUp}`,
          ""
        ])
      : ["No clear decisions were confirmed in the transcript.", ""]),
    "6. Risks / Blockers",
    ...(recap.majorRisks.length
      ? recap.majorRisks.flatMap((item) => [
          `- **${item.title}** — ${item.explanation}. **Impact:** ${item.impact}. **Mitigation / next step:** ${item.mitigationOrNextStep}.`,
          ""
        ])
      : ["None captured.", ""]),
    "7. Open Questions",
    ...renderTextTable(
      ["Question", "Why It Matters", "Owner / Best Next Step"],
      recap.openQuestions.map((item) => [item.question, item.whyItMatters, item.ownerOrBestNextStep])
    ),
    "",
    "8. Reference Notes",
    ...(recap.referenceNotes.length
      ? recap.referenceNotes.flatMap((item) => [item.topic, ...item.notes.map((note) => `- ${note}`), ""])
      : [`Meeting type: ${meetingTypeLabel}`, ""])
  ];
}

function renderExecutiveRecapHtml(input: SummaryEmailInput & { summary: ReturnType<typeof normalizeSummary> }, meetingTypeLabel: string): string {
  const recap = input.summary.executiveRecap;
  const personSpecificBriefs = notesByHeading(input.summary.meetingNotes, "Person-Specific Briefs:");
  const noteGroups = notesByHeading(input.summary.meetingNotes, "Notes:");
  return [
    sectionHeading("1. Executive Highlights"),
    recap.topPriorities.length
      ? `<ol style="margin:0 0 14px 22px;padding:0;font-size:15px;line-height:1.55;color:#374151;">${recap.topPriorities
          .map(
            (item) =>
              `<li style="margin:0 0 10px;"><strong style="color:#111827;">${escapeHtml(item.title)}</strong> — ${escapeHtml(item.summary)}<br>` +
              `<strong>Impact:</strong> ${escapeHtml(item.whyItMatters)}<br>` +
              `<strong>Owner / next step:</strong> ${escapeHtml(item.owner || "Unassigned")}. ${escapeHtml(item.nextStep || "Due TBD")} ${escapeHtml(item.dueDate || "")}</li>`
          )
          .join("")}</ol>`
      : paragraph("None captured.", "margin:0 0 12px;font-size:15px;line-height:1.55;color:#374151;"),
    sectionHeading("2. Person-Specific Briefs"),
    renderMeetingNotesHtml(personSpecificBriefs),
    sectionHeading("3. Notes"),
    recap.detailedRecap.length
      ? recap.detailedRecap.map((item) => `${subHeading(item.heading)}${paragraph(item.summary, "margin:0 0 12px;font-size:15px;line-height:1.55;color:#374151;")}`).join("")
      : "",
    renderMeetingNotesHtml(noteGroups),
    recap.winsAndProgress.length
      ? `${subHeading("Wins & Progress")}<ul style="margin:0 0 14px 20px;padding:0;font-size:15px;line-height:1.55;color:#374151;">${recap.winsAndProgress
          .map((item) => `<li style="margin:0 0 8px;"><strong>${escapeHtml(item.title)}</strong> — ${escapeHtml(item.detail)} <strong>Impact:</strong> ${escapeHtml(item.impact)}</li>`)
          .join("")}</ul>`
      : "",
    recap.detailedRecap.length === 0 && noteGroups.length === 0 && recap.winsAndProgress.length === 0 ? paragraph("No detailed business topics captured.", "margin:0 0 12px;font-size:15px;line-height:1.55;color:#374151;") : "",
    sectionHeading("4. Action Items"),
    subHeading("Immediate Actions"),
    renderHtmlTable(
      ["Priority", "Action", "Owner", "Due", "Related Customer / Area", "Status"],
      recap.immediateActions.map((item) => [item.priority, item.action, item.owner, item.due, item.relatedCustomerOrArea, item.status])
    ),
    subHeading("Full Action Register"),
    renderHtmlTable(
      ["#", "Action", "Owner", "Due", "Priority", "Related Area", "Notes"],
      recap.fullActionRegister.map((item, index) => [String(index + 1), item.action, item.owner, item.due, item.priority, item.relatedArea, item.notes])
    ),
    sectionHeading("5. Decisions"),
    recap.keyDecisions.length
      ? `<ul style="margin:0 0 14px 20px;padding:0;font-size:15px;line-height:1.55;color:#374151;">${recap.keyDecisions
          .map((item) => `<li style="margin:0 0 8px;"><strong>Decision:</strong> ${escapeHtml(item.decision)}<br><strong>Impact:</strong> ${escapeHtml(item.impact)}<br><strong>Owner / follow-up:</strong> ${escapeHtml(item.ownerOrFollowUp)}</li>`)
          .join("")}</ul>`
      : paragraph("No clear decisions were confirmed in the transcript.", "margin:0 0 12px;font-size:15px;line-height:1.55;color:#374151;"),
    sectionHeading("6. Risks / Blockers"),
    recap.majorRisks.length
      ? `<ul style="margin:0 0 14px 20px;padding:0;font-size:15px;line-height:1.55;color:#374151;">${recap.majorRisks
          .map((item) => `<li style="margin:0 0 8px;"><strong>${escapeHtml(item.title)}</strong> — ${escapeHtml(item.explanation)} <strong>Impact:</strong> ${escapeHtml(item.impact)} <strong>Mitigation / next step:</strong> ${escapeHtml(item.mitigationOrNextStep)}</li>`)
          .join("")}</ul>`
      : paragraph("None captured.", "margin:0 0 12px;font-size:15px;line-height:1.55;color:#374151;"),
    sectionHeading("7. Open Questions"),
    renderHtmlTable(
      ["Question", "Why It Matters", "Owner / Best Next Step"],
      recap.openQuestions.map((item) => [item.question, item.whyItMatters, item.ownerOrBestNextStep])
    ),
    sectionHeading("8. Reference Notes"),
    recap.referenceNotes.length
      ? recap.referenceNotes
          .map((item) => `${subHeading(item.topic)}<ul style="margin:0 0 12px 20px;padding:0;font-size:15px;line-height:1.55;color:#374151;">${item.notes.map((note) => `<li style="margin:0 0 5px;">${escapeHtml(note)}</li>`).join("")}</ul>`)
          .join("")
      : paragraph(`Meeting type: ${meetingTypeLabel}`, "margin:0 0 12px;font-size:15px;line-height:1.55;color:#374151;")
  ].join("");
}

function notesByHeading(notes: ReturnType<typeof normalizeSummary>["meetingNotes"], heading: string): ReturnType<typeof normalizeSummary>["meetingNotes"] {
  const normalizedHeading = heading.toLowerCase();
  return notes.filter((note) => note.heading.trim().toLowerCase() === normalizedHeading);
}

function renderTextTable(headers: string[], rows: string[][]): string[] {
  if (rows.length === 0) return ["None captured."];
  const cleanHeaders = headers.map(cleanTableCell);
  return [
    `| ${cleanHeaders.join(" | ")} |`,
    `| ${cleanHeaders.map(() => "---").join(" | ")} |`,
    ...rows.map((row) => `| ${row.map(cleanTableCell).join(" | ")} |`)
  ];
}

function renderHtmlTable(headers: string[], rows: string[][]): string {
  if (rows.length === 0) return paragraph("None captured.", "margin:0 0 12px;font-size:15px;line-height:1.55;color:#374151;");
  const head = headers.map((header) => `<th style="padding:8px;border:1px solid #ddd6fe;text-align:left;background:#f8fafc;color:#111827;">${escapeHtml(header)}</th>`).join("");
  const body = rows
    .map((row) => `<tr>${row.map((cell) => `<td style="padding:8px;border:1px solid #ddd6fe;vertical-align:top;color:#374151;">${escapeHtml(cell)}</td>`).join("")}</tr>`)
    .join("");
  return `<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border-collapse:collapse;width:100%;margin:0 0 14px;font-size:14px;line-height:1.45;"><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table>`;
}

function subHeading(value: string): string {
  return `<h3 style="margin:15px 0 7px;font-size:17px;line-height:1.35;color:#111827;">${escapeHtml(value)}</h3>`;
}

function cleanTableCell(value: string): string {
  return (value || "TBD").replaceAll("|", "/").replace(/\s+/g, " ").trim();
}

function hasExecutiveRecap(recap: ExecutiveRecap): boolean {
  return (
    recap.topPriorities.length > 0 ||
    recap.immediateActions.length > 0 ||
    recap.keyDecisions.length > 0 ||
    recap.majorRisks.length > 0 ||
    recap.detailedRecap.length > 0 ||
    recap.winsAndProgress.length > 0 ||
    recap.fullActionRegister.length > 0 ||
    recap.openQuestions.length > 0 ||
    recap.referenceNotes.length > 0
  );
}

function emptyExecutiveRecap(): ExecutiveRecap {
  return {
    topPriorities: [],
    immediateActions: [],
    keyDecisions: [],
    majorRisks: [],
    detailedRecap: [],
    winsAndProgress: [],
    fullActionRegister: [],
    openQuestions: [],
    referenceNotes: []
  };
}

function resolveLegacySections(input: SummaryEmailInput & { summary: ReturnType<typeof normalizeSummary> }): Array<{ label: string; items: string[] }> {
  const includeActionItems = input.summary.followUpTasks.length === 0;
  const values = {
    summary: input.summary.summary,
    decisions: input.summary.decisions,
    actionItems: includeActionItems ? input.summary.actionItems.map((item) => [item.owner, item.task, item.dueDate].filter(Boolean).join(" - ")) : [],
    openQuestions: input.summary.openQuestions,
    risks: input.summary.risks,
    followUps: input.summary.followUps
  };
  const defaultSections: NonNullable<SummaryEmailInput["recap"]>["sections"] = [
    { key: "summary", label: "Summary", enabled: true },
    { key: "decisions", label: "Decisions", enabled: true },
    { key: "actionItems", label: "Action items", enabled: true },
    { key: "openQuestions", label: "Open questions", enabled: true },
    { key: "risks", label: "Risks", enabled: true },
    { key: "followUps", label: "Follow-ups", enabled: true }
  ];
  return (input.recap?.sections ?? defaultSections)
    .filter((section) => section.enabled)
    .map((section) => ({ label: section.label, items: values[section.key] }));
}

function resolveSecondarySections(input: SummaryEmailInput & { summary: ReturnType<typeof normalizeSummary> }, includeLegacySummary = false): Array<{ label: string; items: string[] }> {
  const labels = includeLegacySummary ? ["Summary", "Decisions", "Open questions", "Risks", "Follow-ups"] : ["Decisions", "Open questions", "Risks"];
  return resolveLegacySections(input).filter((section) => labels.includes(section.label) && section.items.length > 0);
}

function sectionText(title: string, items: string[]): string {
  if (items.length === 0) return "";
  return `${title}\n${items.map((item) => `- ${item}`).join("\n")}\n`;
}

function renderBulletSection(title: string, items: string[]): string {
  if (items.length === 0) return "";
  const listItems = items.map((item) => `<li style="margin:0 0 5px;">${escapeHtml(item)}</li>`).join("");
  return `${sectionHeading(title)}<ul style="margin:0 0 12px 20px;padding:0;font-size:15px;line-height:1.55;color:#374151;">${listItems}</ul>`;
}

function sectionHeading(value: string): string {
  return `<h2 style="margin:23px 0 11px;padding-bottom:7px;border-bottom:1px solid #ddd6fe;font-size:19px;line-height:1.35;color:#111827;">${escapeHtml(value)}</h2>`;
}

function badge(value: string, background = "#ede9fe", color = "#4c1d95"): string {
  return `<span style="display:inline-block;margin:0 6px 6px 0;padding:5px 10px;border-radius:999px;background:${background};background-color:${background};color:${color};font-size:13px;font-weight:800;">${escapeHtml(value)}</span>`;
}

function callout(value: string, background = "#fff7ed", border = "#c2410c", color = "#7c2d12"): string {
  return `<div style="margin:15px 0 0;padding:11px 13px;border-left:4px solid ${border};background:${background};background-color:${background};font-size:15px;line-height:1.5;color:${color};font-weight:800;">${value}</div>`;
}

function paragraph(value: string, style: string): string {
  return `<p style="${style}">${escapeHtml(value)}</p>`;
}

function formatOwners(owners: string[]): string {
  return owners.length > 0 ? owners.join(", ") : "Unassigned";
}

function transcriptExpirationText(hours = defaultTranscriptDownloadExpirationHours): string {
  return `This transcript link expires after ${hours} ${hours === 1 ? "hour" : "hours"}.`;
}

function formatMeetingDate(value: string): string {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;
  return new Intl.DateTimeFormat("en-US", {
    timeZone: "UTC",
    month: "long",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
    timeZoneName: "short"
  }).format(date);
}

function escapeHtml(value: string): string {
  return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
}

function escapeAttribute(value: string): string {
  return escapeHtml(value).replaceAll("'", "&#39;");
}

function isLegacyOnly(summary: ReturnType<typeof normalizeSummary>): boolean {
  return summary.meetingNotes.length === 0 && summary.followUpTasks.length === 0;
}
