import { meetingRecapTypeLabels } from "@minutesbot/summary-engine";
import type { RenderedEmail, SummaryEmailInput, SummaryEmailSummary } from "./types";

const aiDisclaimer = "Generated by AI. Be sure to check for accuracy.";
const footerSenderText = "Sent by minutesbot";
const footerReviewText = "This recap was generated by AI from the meeting transcript and may require human review.";
const defaultTranscriptDownloadExpirationHours = 24;

export function renderSummaryEmail(input: SummaryEmailInput): RenderedEmail {
  const summary = normalizeSummary(input.summary);
  const meetingTypeLabel = meetingRecapTypeLabels[summary.meetingType];
  const recapDepthLabel = summary.recapDepth === "brief" ? "Brief" : "Standard";
  const text = renderText({ ...input, summary }, meetingTypeLabel, recapDepthLabel);
  const html = renderHtml({ ...input, summary }, meetingTypeLabel, recapDepthLabel);
  return { subject: `${input.recap?.subjectPrefix ?? "Meeting summary"}: ${input.subject}`, text, html };
}

function normalizeSummary(summary: SummaryEmailSummary): Required<Pick<SummaryEmailSummary, "meetingType" | "recapDepth" | "meetingNotes" | "followUpTasks">> & SummaryEmailSummary {
  return {
    ...summary,
    meetingType: summary.meetingType ?? "general",
    recapDepth: summary.recapDepth ?? "standard",
    meetingNotes: summary.meetingNotes ?? [],
    followUpTasks: summary.followUpTasks ?? []
  };
}

function renderText(input: SummaryEmailInput & { summary: ReturnType<typeof normalizeSummary> }, meetingTypeLabel: string, recapDepthLabel: string): string {
  const secondarySections = resolveSecondarySections(input, isLegacyOnly(input.summary));
  const displayDate = input.date ? formatMeetingDate(input.date) : "";
  return [
    aiDisclaimer,
    "",
    "Meeting recap",
    `Subject: ${input.subject}`,
    displayDate ? `Date: ${displayDate}` : "",
    `Meeting type: ${meetingTypeLabel}`,
    `Recap depth: ${recapDepthLabel}`,
    input.transcriptDownloadUrl ? `Download Transcript: ${input.transcriptDownloadUrl}` : "",
    input.transcriptDownloadUrl ? transcriptExpirationText(input.transcriptDownloadExpirationHours) : "",
    input.recap?.introText ?? "",
    input.summary.recapDepth === "brief" ? "Brief meeting detected. This recap is simplified because the meeting or captured transcript was very short." : "",
    "",
    "Meeting notes:",
    "",
    ...renderMeetingNotesText(input.summary.meetingNotes),
    "Follow-up tasks:",
    "",
    ...renderFollowUpTasksText(input.summary.followUpTasks),
    ...secondarySections.map((section) => sectionText(section.label, section.items)),
    sectionText("Not sent to external attendees", input.excludedRecipients ?? [])
  ]
    .filter(Boolean)
    .join("\n");
}

function renderHtml(input: SummaryEmailInput & { summary: ReturnType<typeof normalizeSummary> }, meetingTypeLabel: string, recapDepthLabel: string): string {
  const secondarySections = resolveSecondarySections(input, isLegacyOnly(input.summary));
  return [
    '<meta name="color-scheme" content="light only">',
    '<meta name="supported-color-schemes" content="light">',
    "<style>:root { color-scheme: only light; supported-color-schemes: light; }</style>",
    '<div style="margin:0;padding:0 8px 18px;background:#ffffff;background-color:#ffffff;font-family:Inter,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#111827;color-scheme:only light;">',
    '<div style="max-width:760px;margin:0 auto;background:#ffffff;background-color:#ffffff;border:1px solid #c4b5fd;border-radius:10px;overflow:hidden;color:#111827;">',
    '<div style="height:4px;background:#5b21b6;background-color:#5b21b6;"></div>',
    '<div style="padding:14px 20px 20px;background:#ffffff;background-color:#ffffff;color:#111827;">',
    renderHeader(input, meetingTypeLabel),
    callout(aiDisclaimer),
    input.summary.recapDepth === "brief" ? callout("Brief meeting detected<br><span style=\"font-weight:650;\">This recap is simplified because the meeting or captured transcript was very short.</span>", "#eef2ff", "#4338ca", "#312e81") : "",
    input.recap?.introText ? paragraph(input.recap.introText, "margin:15px 0 0;font-size:15px;line-height:1.55;color:#374151;") : "",
    sectionHeading("Meeting notes"),
    renderMeetingNotesHtml(input.summary.meetingNotes),
    sectionHeading("Follow-up tasks"),
    renderFollowUpTasksHtml(input.summary.followUpTasks),
    secondarySections.map((section) => renderBulletSection(section.label, section.items)).join(""),
    input.excludedRecipients?.length ? renderBulletSection("Not sent to external attendees", input.excludedRecipients) : "",
    `<div style="margin-top:22px;padding-top:13px;border-top:1px solid #c4b5fd;color:#374151;font-size:13px;line-height:1.5;">${footerSenderText}<br>${footerReviewText}</div>`,
    "</div></div></div>"
  ].join("");
}

function renderHeader(input: SummaryEmailInput & { summary: ReturnType<typeof normalizeSummary> }, meetingTypeLabel: string): string {
  const displayDate = input.date ? formatMeetingDate(input.date) : "";
  return [
    '<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border-collapse:collapse;width:100%;margin:0 0 4px;">',
    "<tr>",
    '<td valign="top" style="padding:0 16px 0 0;">',
    '<div style="font-size:13px;letter-spacing:.08em;text-transform:uppercase;color:#5b21b6;font-weight:800;">MINUTESBOT</div>',
    '<h1 style="margin:6px 0 5px;font-size:27px;line-height:1.18;color:#111827;">Meeting recap</h1>',
    paragraph(input.subject, "margin:0;font-size:18px;line-height:1.4;color:#111827;font-weight:800;"),
    "</td>",
    '<td valign="top" align="right" style="padding:2px 0 0 16px;text-align:right;">',
    displayDate ? paragraph(displayDate, "margin:0 0 9px;font-size:15px;line-height:1.4;color:#374151;") : "",
    `<div style="display:block;margin:0;">${badge(meetingTypeLabel)}${input.summary.recapDepth === "brief" ? badge("Brief recap", "#eef2ff", "#312e81") : ""}</div>`,
    input.transcriptDownloadUrl
      ? `<p style="margin:6px 0 0;font-size:15px;line-height:1.4;"><a href="${escapeAttribute(input.transcriptDownloadUrl)}" style="color:#5b21b6;font-weight:800;text-decoration:underline;">Download Transcript</a></p>` +
        paragraph(transcriptExpirationText(input.transcriptDownloadExpirationHours), "margin:2px 0 0;font-size:13px;line-height:1.4;color:#4b5563;")
      : "",
    "</td>",
    "</tr>",
    "</table>"
  ].join("");
}

function renderMeetingNotesText(notes: ReturnType<typeof normalizeSummary>["meetingNotes"]): string[] {
  if (notes.length === 0) return ["None captured.", ""];
  return notes.flatMap((note) => {
    const overview = shouldRenderMeetingNoteOverview(note.overview) ? note.overview : "";
    return [
      note.heading,
      overview,
      ...note.items.flatMap((item) => [item.title, item.detail, ""]),
      ""
    ];
  });
}

function renderFollowUpTasksText(tasks: ReturnType<typeof normalizeSummary>["followUpTasks"]): string[] {
  if (tasks.length === 0) return ["No follow-up tasks captured.", ""];
  return tasks.flatMap((task) => [
    task.title,
    task.description,
    `Owner: ${formatOwners(task.owners)}`,
    `Due: ${task.dueDate}`,
    ""
  ]);
}

function renderMeetingNotesHtml(notes: ReturnType<typeof normalizeSummary>["meetingNotes"]): string {
  if (notes.length === 0) return paragraph("None captured.", "margin:0 0 12px;font-size:15px;line-height:1.55;color:#374151;");
  return notes
    .map(
      (note) =>
        `<div style="margin:0 0 14px;padding:0 0 14px;border-bottom:1px solid #ede9fe;">` +
        `<h3 style="margin:0 0 7px;font-size:17px;line-height:1.35;color:#111827;">${escapeHtml(note.heading)}</h3>` +
        (shouldRenderMeetingNoteOverview(note.overview) ? paragraph(note.overview, "margin:0 0 11px;font-size:15px;line-height:1.55;color:#374151;") : "") +
        note.items
          .map((item) => `<p style="margin:9px 0 4px;font-size:15px;line-height:1.45;color:#111827;"><strong style="color:#111827;">${escapeHtml(item.title)}</strong></p>${paragraph(item.detail, "margin:0;font-size:15px;line-height:1.55;color:#374151;")}`)
          .join("") +
        "</div>"
    )
    .join("");
}

function shouldRenderMeetingNoteOverview(value: string): boolean {
  return value.trim() !== "" && value.trim() !== aiDisclaimer;
}

function renderFollowUpTasksHtml(tasks: ReturnType<typeof normalizeSummary>["followUpTasks"]): string {
  if (tasks.length === 0) return paragraph("No follow-up tasks captured.", "margin:0 0 12px;font-size:15px;line-height:1.55;color:#374151;");
  return tasks
    .map(
      (task) =>
        `<div style="margin:0 0 12px;padding:11px 12px 11px 13px;border-left:4px solid #5b21b6;border-top:1px solid #ddd6fe;border-right:1px solid #ddd6fe;border-bottom:1px solid #ddd6fe;background:#ffffff;background-color:#ffffff;color:#111827;">` +
        `<p style="margin:0 0 5px;font-size:15px;line-height:1.45;color:#111827;"><strong style="color:#111827;">${escapeHtml(task.title)}</strong></p>` +
        paragraph(task.description, "margin:0 0 7px;font-size:15px;line-height:1.55;color:#374151;") +
        paragraph(`Owner: ${formatOwners(task.owners)}`, "margin:0 0 3px;font-size:13px;line-height:1.45;color:#4b5563;") +
        paragraph(`Due: ${task.dueDate}`, "margin:0;font-size:13px;line-height:1.45;color:#4b5563;") +
        "</div>"
    )
    .join("");
}

function resolveLegacySections(input: SummaryEmailInput & { summary: ReturnType<typeof normalizeSummary> }): Array<{ label: string; items: string[] }> {
  const includeActionItems = input.summary.followUpTasks.length === 0;
  const values = {
    summary: input.summary.summary,
    decisions: input.summary.decisions,
    actionItems: includeActionItems ? input.summary.actionItems.map((item) => [item.owner, item.task, item.dueDate].filter(Boolean).join(" - ")) : [],
    openQuestions: input.summary.openQuestions,
    risks: input.summary.risks,
    followUps: input.summary.followUps
  };
  const defaultSections: NonNullable<SummaryEmailInput["recap"]>["sections"] = [
    { key: "summary", label: "Summary", enabled: true },
    { key: "decisions", label: "Decisions", enabled: true },
    { key: "actionItems", label: "Action items", enabled: true },
    { key: "openQuestions", label: "Open questions", enabled: true },
    { key: "risks", label: "Risks", enabled: true },
    { key: "followUps", label: "Follow-ups", enabled: true }
  ];
  return (input.recap?.sections ?? defaultSections)
    .filter((section) => section.enabled)
    .map((section) => ({ label: section.label, items: values[section.key] }));
}

function resolveSecondarySections(input: SummaryEmailInput & { summary: ReturnType<typeof normalizeSummary> }, includeLegacySummary = false): Array<{ label: string; items: string[] }> {
  const labels = includeLegacySummary ? ["Summary", "Decisions", "Open questions", "Risks", "Follow-ups"] : ["Decisions", "Open questions", "Risks"];
  return resolveLegacySections(input).filter((section) => labels.includes(section.label) && section.items.length > 0);
}

function sectionText(title: string, items: string[]): string {
  if (items.length === 0) return "";
  return `${title}\n${items.map((item) => `- ${item}`).join("\n")}\n`;
}

function renderBulletSection(title: string, items: string[]): string {
  if (items.length === 0) return "";
  const listItems = items.map((item) => `<li style="margin:0 0 5px;">${escapeHtml(item)}</li>`).join("");
  return `${sectionHeading(title)}<ul style="margin:0 0 12px 20px;padding:0;font-size:15px;line-height:1.55;color:#374151;">${listItems}</ul>`;
}

function sectionHeading(value: string): string {
  return `<h2 style="margin:23px 0 11px;padding-bottom:7px;border-bottom:1px solid #ddd6fe;font-size:19px;line-height:1.35;color:#111827;">${escapeHtml(value)}</h2>`;
}

function badge(value: string, background = "#ede9fe", color = "#4c1d95"): string {
  return `<span style="display:inline-block;margin:0 6px 6px 0;padding:5px 10px;border-radius:999px;background:${background};background-color:${background};color:${color};font-size:13px;font-weight:800;">${escapeHtml(value)}</span>`;
}

function callout(value: string, background = "#fff7ed", border = "#c2410c", color = "#7c2d12"): string {
  return `<div style="margin:15px 0 0;padding:11px 13px;border-left:4px solid ${border};background:${background};background-color:${background};font-size:15px;line-height:1.5;color:${color};font-weight:800;">${value}</div>`;
}

function paragraph(value: string, style: string): string {
  return `<p style="${style}">${escapeHtml(value)}</p>`;
}

function formatOwners(owners: string[]): string {
  return owners.length > 0 ? owners.join(", ") : "Unassigned";
}

function transcriptExpirationText(hours = defaultTranscriptDownloadExpirationHours): string {
  return `This transcript link expires after ${hours} ${hours === 1 ? "hour" : "hours"}.`;
}

function formatMeetingDate(value: string): string {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;
  return new Intl.DateTimeFormat("en-US", {
    timeZone: "UTC",
    month: "long",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
    timeZoneName: "short"
  }).format(date);
}

function escapeHtml(value: string): string {
  return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
}

function escapeAttribute(value: string): string {
  return escapeHtml(value).replaceAll("'", "&#39;");
}

function isLegacyOnly(summary: ReturnType<typeof normalizeSummary>): boolean {
  return summary.meetingNotes.length === 0 && summary.followUpTasks.length === 0;
}
