import { describe, expect, it } from "vitest";
import { renderFailureEmail, renderSummaryEmail } from "./index";

describe("email renderer", () => {
  it("renders summary text and html snapshots", () => {
    const rendered = renderSummaryEmail({
      subject: "Project sync",
      date: "2026-05-07T14:00:00.000Z",
      summary: {
        meetingType: "general",
        recapDepth: "standard",
        meetingNotes: [
          {
            heading: "Key Discussion Topics:",
            overview: "The launch path was reviewed.",
            items: [{ title: "Launch Readiness:", detail: "Alex reviewed launch readiness and confirmed release notes still need to be shipped." }]
          }
        ],
        followUpTasks: [{ title: "Ship Release Notes:", description: "Ship release notes for the launch package.", owners: ["Alex"], dueDate: "TBD" }],
        summary: ["Discussed launch."],
        decisions: [],
        actionItems: [{ owner: "Alex", task: "Ship release notes", dueDate: "TBD" }],
        openQuestions: [],
        risks: [],
        followUps: []
      },
      excludedRecipients: ["vendor@example.com"],
      transcriptDownloadUrl: "https://minutesbot.example.com/api/artifacts/mtg_1/transcript.txt?token=test"
    });

    expect(rendered.subject).toBe("Meeting summary: Project sync");
    expect(rendered.text).toContain("Generated by AI. Be sure to check for accuracy.");
    expect(rendered.text).toContain("Date: May 7, 2026 at 2:00 PM UTC");
    expect(rendered.text).not.toContain("Date: 2026-05-07T14:00:00.000Z");
    expect(rendered.text).toContain("Meeting type: General");
    expect(rendered.text).toContain("Recap depth: Standard");
    expect(rendered.text).toContain("Download Transcript: https://minutesbot.example.com/api/artifacts/mtg_1/transcript.txt?token=test");
    expect(rendered.text).toContain("This transcript link expires after 24 hours.");
    expect(rendered.text).toContain("Meeting notes:");
    expect(rendered.text).toContain("Key Discussion Topics:");
    expect(rendered.text).toContain("Launch Readiness:");
    expect(rendered.text).toContain("Follow-up tasks:");
    expect(rendered.text).toContain("Ship Release Notes:");
    expect(rendered.text).toContain("Owner: Alex");
    expect(rendered.text).toContain("Due: TBD");
    expect(rendered.html).toContain("vendor@example.com");
    expect(rendered.html).toContain("Generated by AI. Be sure to check for accuracy.");
    expect(rendered.html).toContain("May 7, 2026 at 2:00 PM UTC");
    expect(rendered.html).not.toContain("2026-05-07T14:00:00.000Z");
    expect(rendered.html).toContain("Download Transcript");
    expect(rendered.html).toContain("This transcript link expires after 24 hours.");
    expect(rendered.html).not.toContain("Download raw transcript");
    expect(rendered.html).toContain("Meeting notes");
    expect(rendered.html).toContain("Key Discussion Topics:");
    expect(rendered.html).toContain('<strong style="color:#111827;">Launch Readiness:</strong>');
    expect(rendered.html).toContain("Follow-up tasks");
    expect(rendered.html).toContain("MINUTESBOT");
    expect(rendered.html).not.toContain("Legacy brand / minutesbot");
    expect(rendered.html).toContain("Sent by minutesbot");
    expect(rendered.html).not.toContain("Sent by legacy fork of minutesbot");
    expect(rendered.html).toContain("This recap was generated by AI from the meeting transcript and may require human review.");
    expect(rendered.html).toContain('<meta name="color-scheme" content="light only">');
    expect(rendered.html).toContain('<meta name="supported-color-schemes" content="light">');
    expect(rendered.html).toContain("color-scheme: only light");
    expect(rendered.html).toContain("supported-color-schemes: light");
    expect(rendered.html).toContain("background:#ffffff");
    expect(rendered.html).toContain("padding:0 8px 18px");
    expect(rendered.html).toContain("max-width:760px");
    expect(rendered.html).toContain('<table role="presentation" width="100%"');
    expect(rendered.html).toContain("align=\"right\"");
    expect(rendered.html).toContain("#5b21b6");
    expect(rendered.html).toContain("#ede9fe");
    expect(rendered.html).toContain("#4c1d95");
    expect(rendered.html).toContain("#fff7ed");
    expect(rendered.html).toContain("#7c2d12");
    expect(rendered.html).toContain("border-left:4px solid #5b21b6");
    expect(rendered.html).toContain("background:#ffffff;background-color:#ffffff;color:#111827");
    expect(rendered.html).not.toContain("background:#111827");
    expect(rendered.html).not.toContain("background:#0b1120");
    expect(rendered.html).not.toContain("background:#f5f3ff");
    expect(rendered.html).not.toContain("#334155");
    expect(rendered.html).not.toContain("#cbd5e1");
    expect(rendered.html).not.toContain("font-size:12px");
    expect(rendered.html).not.toContain("border:1px solid #dbe6ea");
  });

  it("renders organizer-only failure notices", () => {
    expect(renderFailureEmail({ subject: "Project sync" }).subject).toBe("Notes unavailable: Project sync");
  });

  it("renders recap layout settings in configured order", () => {
    const rendered = renderSummaryEmail({
      subject: "Project sync",
      summary: {
        meetingType: "general",
        recapDepth: "standard",
        meetingNotes: [
          {
            heading: "Key Discussion Topics:",
            overview: "The launch checklist was reviewed.",
            items: [{ title: "Launch Checklist:", detail: "The team reviewed checklist ownership and training gaps." }]
          }
        ],
        followUpTasks: [{ title: "Ship Release Notes:", description: "Ship release notes for the launch package.", owners: ["Alex"], dueDate: "TBD" }],
        summary: ["Discussed launch."],
        decisions: ["Launch Friday."],
        actionItems: [{ owner: "Alex", task: "Ship release notes", dueDate: "TBD" }],
        openQuestions: ["Who owns training?"],
        risks: ["Schedule compression."],
        followUps: ["Review launch checklist."]
      },
      recap: {
        subjectPrefix: "Recap",
        introText: "Here is the meeting recap.",
        sections: [
          { key: "actionItems", label: "Next steps", enabled: true },
          { key: "summary", label: "Overview", enabled: true },
          { key: "risks", label: "Risks", enabled: false }
        ]
      }
    });

    expect(rendered.subject).toBe("Recap: Project sync");
    expect(rendered.text).toContain("Follow-up tasks:");
    expect(rendered.text).not.toContain("Next steps");
    expect(rendered.text).toContain("Here is the meeting recap.");
    expect(rendered.text).not.toContain("Schedule compression.");
    expect(rendered.html).toContain("Here is the meeting recap.");
  });

  it("renders meeting type in plain text and html and treats legacy summaries as general", () => {
    const typed = renderSummaryEmail({
      subject: "Weekly Sales",
      summary: {
        meetingType: "weekly_sales",
        recapDepth: "brief",
        meetingNotes: [
          {
            heading: "Sales Pipeline and Forecast Updates:",
            overview: "Forecast movement was reviewed.",
            items: [{ title: "Forecast Movement:", detail: "Forecast moved up based on current pipeline movement." }]
          }
        ],
        followUpTasks: [],
        summary: ["Meeting type: Weekly Sales", "Sales forecast/pipeline: Forecast moved up."],
        decisions: [],
        actionItems: [],
        openQuestions: [],
        risks: [],
        followUps: []
      }
    });
    const legacy = renderSummaryEmail({
      subject: "Old summary",
      summary: {
        summary: ["Discussed launch."],
        decisions: [],
        actionItems: [],
        openQuestions: [],
        risks: [],
        followUps: []
      }
    });

    expect(typed.text).toContain("Meeting type: Weekly Sales");
    expect(typed.text).toContain("Recap depth: Brief");
    expect(typed.text).toContain("Brief meeting detected.");
    expect(typed.html).toContain("Weekly Sales");
    expect(typed.html).toContain("Brief recap");
    expect(typed.html).toContain("Brief meeting detected");
    expect(legacy.text).toContain("Generated by AI. Be sure to check for accuracy.");
    expect(legacy.text).toContain("Meeting type: General");
    expect(legacy.text).toContain("Recap depth: Standard");
    expect(legacy.text).toContain("Summary");
  });

  it("does not repeat the AI disclaimer as a brief recap note overview", () => {
    const rendered = renderSummaryEmail({
      subject: "Short test",
      summary: {
        meetingType: "general",
        recapDepth: "brief",
        meetingNotes: [
          {
            heading: "Brief meeting recap",
            overview: "Generated by AI. Be sure to check for accuracy.",
            items: [{ title: "What happened", detail: "A very short test meeting was captured." }]
          }
        ],
        followUpTasks: [],
        summary: ["A short test meeting was captured."],
        decisions: [],
        actionItems: [],
        openQuestions: [],
        risks: [],
        followUps: []
      }
    });

    expect(rendered.text.match(/Generated by AI\. Be sure to check for accuracy\./g)).toHaveLength(1);
    expect(rendered.html.match(/Generated by AI\. Be sure to check for accuracy\./g)).toHaveLength(1);
    expect(rendered.text).toContain("What happened");
    expect(rendered.html).toContain("What happened");
  });

  it("escapes model-provided html content", () => {
    const rendered = renderSummaryEmail({
      subject: "Project <sync>",
      summary: {
        meetingType: "general",
        recapDepth: "standard",
        meetingNotes: [
          {
            heading: "Topic <script>:",
            overview: "Overview <b>bold</b>",
            items: [{ title: "Item <x>:", detail: "Detail <img src=x onerror=alert(1)>" }]
          }
        ],
        followUpTasks: [{ title: "Task <bad>:", description: "Do <thing>", owners: ["Alex <admin>"], dueDate: "TBD <soon>" }],
        summary: [],
        decisions: [],
        actionItems: [],
        openQuestions: [],
        risks: [],
        followUps: []
      },
      transcriptDownloadUrl: "https://example.com/transcript?token=a&b=c"
    });

    expect(rendered.html).toContain("Project &lt;sync&gt;");
    expect(rendered.html).toContain("Topic &lt;script&gt;:");
    expect(rendered.html).toContain("Overview &lt;b&gt;bold&lt;/b&gt;");
    expect(rendered.html).toContain("https://example.com/transcript?token=a&amp;b=c");
    expect(rendered.html).not.toContain("<script>");
    expect(rendered.html).not.toContain("<img");
  });
});
