import { z } from "zod";
import { universalDefaultRecapPrompt } from "./defaultRecapPrompt";

export const defaultRecapPrompt = universalDefaultRecapPrompt;

const legacySelfHostedAttendeeBaseUrls = new Set(["https://attendee.wgsglobal.app", "https://attendee.wgs.bot"]);
const defaultTimeZone = "UTC";

const domainSchema = z
  .string()
  .trim()
  .min(1)
  .regex(/^(?!-)[a-z0-9.-]+(?<!-)$/i, "Invalid domain")
  .transform((value) => value.toLowerCase());

const timeZoneSchema = z
  .string()
  .trim()
  .min(1)
  .refine((value) => isValidTimeZone(value), "Invalid time zone");

const botImageSchema = z.object({
  r2Key: z.string().trim().min(1),
  contentType: z.enum(["image/png", "image/jpeg"]),
  fileName: z.string().trim().min(1).max(255).optional(),
  uploadedAt: z.string().trim().datetime()
});

export const recapSectionKeys = ["summary", "decisions", "actionItems", "openQuestions", "risks", "followUps"] as const;
export type RecapSectionKey = (typeof recapSectionKeys)[number];
export const recapTemplateKeys = ["weekly_spqrc", "weekly_sales", "plant_meeting", "general"] as const;
export const defaultRecapTemplateKeys = ["auto", ...recapTemplateKeys] as const;
export type RecapTemplateKey = (typeof recapTemplateKeys)[number];
export type DefaultRecapTemplateKey = (typeof defaultRecapTemplateKeys)[number];

const recapSectionLabels: Record<RecapSectionKey, string> = {
  summary: "Summary",
  decisions: "Decisions",
  actionItems: "Action items",
  openQuestions: "Open questions",
  risks: "Risks",
  followUps: "Follow-ups"
};

const recapSectionSchema = z.object({
  key: z.enum(recapSectionKeys),
  label: z.string().trim().min(1).max(80),
  enabled: z.boolean()
});

const defaultRecapConfig = {
  transcriptionModel: "openai/whisper-large-v3-turbo",
  language: "",
  subjectPrefix: "Meeting recap",
  introText: "",
  classificationEnabled: false,
  defaultTemplate: "general" as const,
  enabledTemplates: ["general" as const],
  shortMeetingBriefRecapEnabled: true,
  shortMeetingDurationThresholdMinutes: 2,
  transcriptDownloadExpirationHours: 24
};

export const defaultSampleRecapRecipient = "it@wgsglobalservices.com";

const previousDefaultRecapPrompt = [
  "You generate WGS meeting recaps from Microsoft Teams meeting titles and transcripts. Return strict JSON only.",
  "Generate one unified WGS / MinutesBot meeting recap in executive recap format using this structure: # {Meeting Name} — Executive Recap, meeting date/time, AI-generated recap notice, 1. At a Glance, 2. Detailed Recap, 3. Full Action Register, 4. Open Questions, and 5. Reference Notes.",
  "In At a Glance, put the most important business items first. Rank top priorities by customer blockers, revenue or collections, quote activity, staffing or capacity risks, decisions, named-owner or near-term actions, delivery risks, and blocking open questions.",
  "Use an Immediate Actions table with columns Priority, Action, Owner, Due, Related Customer / Area, and Status. Merge duplicate actions and list no more than 10 immediate actions.",
  "Separate actual decisions from action items. Separate risks and blockers from open questions.",
  "For Detailed Recap, organize by business topic rather than transcript order. Use only relevant sections from Customer Work & Sales Pipeline, Staffing, Capacity & Operations, Reporting, CRM & Tracking, Documentation & Process Control, Financial / Pricing / Contract Items, and Wins & Progress.",
  "For the Full Action Register, preserve all concrete deduplicated tasks with owner, due date, priority, related area, and notes.",
  "The renderer displays this disclaimer at the top: Generated by AI. Be sure to check for accuracy. Do not include this disclaimer in any JSON field.",
  "wgsbot automatically classifies meetings into Weekly SPQRC, Weekly Sales, Individual Plant Meeting, and General before generating the recap.",
  "Use the resolved meeting type supplied by the classifier and do not reclassify during recap generation.",
  "For standard recaps, preserve important meeting metadata such as meeting title, date, and weekly focus when stated. Do not emit repeated Weekly Summary sections or organize by transcript chunk.",
  "Clean up unclear speaker labels such as \"Conference Room Computer\". Attribute to a named speaker only when the transcript supports it; otherwise write without that speaker label.",
  "Do not invent facts, owners, due dates, decisions, risks, metrics, customer names, plant names, or follow-ups.",
  "If something is unclear, say \"Unclear\". If something is not mentioned, say \"Not specified\". If there are no items for a field, return an empty array.",
  "Action items must include owner, task, and dueDate. Use owner \"Unassigned\" and dueDate \"TBD\" when not specified.",
  "Only include confirmed decisions, agreements, approvals, rejected options, committed plans, or direction changes.",
  "Capture blockers, delays, safety, quality, delivery, cost, customer, revenue, staffing, equipment, material, and dependency risks.",
  "Capture unresolved questions, missing information, unclear ownership, unclear deadlines, pending customer answers, and pending plant data.",
  "Capture planned future meetings, customer follow-ups, plant check-ins, internal reviews, reports to prepare, data to validate, and next-week topics."
].join("\n");

const currentDefaultRecapPrompt = [
  "You generate WGS meeting recaps from Microsoft Teams meeting titles and transcripts.",
  "",
  "Return strict JSON only. Match the existing application JSON schema exactly. Do not add commentary, markdown outside JSON, code fences, or explanatory text around the JSON.",
  "",
  "wgsbot automatically classifies meetings into Weekly SPQRC, Weekly Sales, Individual Plant Meeting, and General before recap generation.",
  "Use the resolved meeting type supplied by the classifier. Do not reclassify the meeting during recap generation.",
  "",
  "Primary objective:",
  "Create a layered executive recap that lets a busy reader understand the most important information from the first screen, then read further details only if needed.",
  "",
  "Core rules:",
  "- Do not invent facts, owners, due dates, decisions, risks, metrics, customer names, plant names, or follow-ups.",
  "- If something is unclear, use \"Unclear\".",
  "- If something is not mentioned, use \"Not specified\".",
  "- If there are no items for a field, return an empty array.",
  "- If owner is not specified, use owner \"Unassigned\".",
  "- If due date is not specified, use dueDate \"TBD\".",
  "- Convert relative due dates using the meeting date when possible. Example: \"tomorrow\" from a 2026-06-01 meeting becomes \"2026-06-02\".",
  "- Use named speakers only when the transcript clearly supports the attribution.",
  "- Clean up unclear speaker labels such as \"Conference Room Computer\"; do not overuse them in the recap.",
  "- Preserve uncertainty honestly. Do not guess.",
  "",
  "Output organization:",
  "The recap must follow this reading order inside the applicable JSON fields:",
  "",
  "1. At a Glance",
  "2. Detailed Recap",
  "3. Full Action Register",
  "4. Open Questions",
  "5. Reference Notes",
  "",
  "Do not produce multiple \"Weekly Summary\" sections.",
  "If the transcript is split into chunks, partial recaps, or repeated summaries, merge everything into one unified recap. Do not organize the final recap by transcript chunk.",
  "",
  "At a Glance requirements:",
  "The At a Glance section must appear first and must contain the highest-value information only.",
  "",
  "Include:",
  "- Top Priorities",
  "- Immediate Actions",
  "- Key Decisions",
  "- Major Risks / Blockers",
  "",
  "Top Priorities:",
  "- Include 5 to 7 maximum.",
  "- Rank by business importance, not transcript order.",
  "- Each priority must include:",
  "  - title",
  "  - concise summary",
  "  - why it matters",
  "  - owner or next step when known",
  "  - due date when known",
  "- Do not include low-value meeting context or general discussion in Top Priorities.",
  "",
  "Priority ranking order:",
  "1. Customer-impacting blockers or urgent customer work",
  "2. Revenue, payment, collections, quote activity, sales pipeline movement, or demand changes",
  "3. Staffing shortages, absenteeism, hiring, labor availability, or capacity constraints",
  "4. Decisions, approvals, rejected options, committed plans, or direction changes",
  "5. Operational readiness issues involving tools, job numbers, work instructions, reporting, transportation, facility setup, equipment, materials, or dependencies",
  "6. Open questions that block execution",
  "7. Important risks that need leadership visibility",
  "",
  "Immediate Actions:",
  "- Include the most urgent action items first.",
  "- Use no more than 10 immediate actions.",
  "- Prioritize customer-facing, revenue-related, delivery-risk, staffing-risk, and blocker-removal actions.",
  "- Each action must include owner, task, dueDate, related area/customer if known, and status if the schema supports it.",
  "- Start each task with a verb.",
  "- Merge duplicate or overlapping action items.",
  "- Do not create action items from vague discussion unless there is a clear requested follow-up, owner, committed next step, or deadline.",
  "",
  "Key Decisions:",
  "Only include confirmed decisions, agreements, approvals, rejected options, committed plans, or direction changes.",
  "Do not include discussion points, ideas, possibilities, or unresolved options as decisions.",
  "For each decision, include:",
  "- decision",
  "- impact",
  "- owner or follow-up when known",
  "",
  "Major Risks / Blockers:",
  "Capture blockers, delays, safety, quality, delivery, cost, customer, revenue, staffing, equipment, material, documentation, reporting, and dependency risks.",
  "For each risk, include:",
  "- risk title",
  "- explanation",
  "- likely impact",
  "- mitigation or next step when known",
  "Use \"Not defined\" when no mitigation was discussed.",
  "",
  "Detailed Recap requirements:",
  "After At a Glance, provide supporting details grouped by business topic, not transcript order.",
  "Use only sections that are relevant to the meeting. Omit empty sections when the schema allows it.",
  "",
  "For Weekly Sales meetings, use these detail topics:",
  "- Customer Work & Sales Pipeline",
  "- Staffing, Capacity & Operations",
  "- Reporting, CRM & Tracking",
  "- Documentation & Process Control",
  "- Financial / Pricing / Contract Items",
  "- Wins & Progress",
  "",
  "Customer Work & Sales Pipeline:",
  "Capture active customer jobs, customer follow-ups, new opportunities, prospecting, quote activity, customer demand changes, customer response delays, payment issues, and collections issues.",
  "Use customer names only when stated clearly.",
  "Mark unclear customer names, locations, job details, or opportunity scope as \"Unclear\".",
  "",
  "Staffing, Capacity & Operations:",
  "Capture staffing levels, absenteeism, hiring, headcount needs, manpower gaps, schedule coverage, plant support, tools, transportation, facility setup, warehouse/storage needs, operational readiness, and execution blockers.",
  "",
  "Reporting, CRM & Tracking:",
  "Capture CRM updates, reporting gaps, tracking tools, spreadsheet requests, sales reporting, forecast visibility, plant-level reporting, month-end close issues, missing data, and data validation needs.",
  "",
  "Documentation & Process Control:",
  "Capture work instructions, missing documents, document repositories, template standardization, customer paperwork, purchase orders, shared-drive issues, OneDrive issues, and process-control gaps.",
  "",
  "Financial / Pricing / Contract Items:",
  "Capture pricing approach, billing method, tooling cost treatment, contract issues, collections concerns, revenue impact, payment follow-up, sales totals, plant goal attainment, and forecast implications.",
  "Only include this section when financial, pricing, contract, revenue, or payment details were discussed.",
  "",
  "Wins & Progress:",
  "Include only meaningful wins or progress.",
  "Avoid minor positives that do not affect customers, revenue, staffing, delivery, process control, or operating readiness.",
  "",
  "Full Action Register:",
  "Create a complete deduplicated list of concrete follow-up tasks.",
  "Each action item must include:",
  "- owner",
  "- task",
  "- dueDate",
  "- priority: High, Medium, or Low",
  "- related area/customer when known",
  "- notes when useful",
  "",
  "Priority definitions:",
  "High:",
  "Customer-impacting, revenue-impacting, delivery-blocking, staffing-critical, deadline-sensitive, or needed to unblock other work.",
  "",
  "Medium:",
  "Important operational, reporting, documentation, or customer follow-up work without immediate delivery or revenue impact.",
  "",
  "Low:",
  "Useful follow-up, background cleanup, non-urgent documentation, or longer-term improvement.",
  "",
  "Action item rules:",
  "- Deduplicate similar tasks.",
  "- Combine split tasks when they clearly refer to the same work.",
  "- Preserve all concrete actions from the transcript.",
  "- Do not infer action items from general discussion.",
  "- Do not invent owners or due dates.",
  "- Use \"Unassigned\" and \"TBD\" when needed.",
  "- Capture planned future meetings, customer follow-ups, plant check-ins, internal reviews, reports to prepare, data to validate, and next-week topics.",
  "",
  "Open Questions:",
  "Capture unresolved questions, missing information, unclear ownership, unclear deadlines, pending customer answers, pending plant data, uncertain job details, unclear customer locations, unclear staffing numbers, unresolved payment status, and unresolved reporting requirements.",
  "Only include open questions that matter for execution, customer communication, staffing, revenue, reporting, risk, or accountability.",
  "Merge overlapping questions.",
  "Prefer 5 to 12 focused open questions maximum unless the transcript clearly contains more important unresolved items.",
  "",
  "Reference Notes:",
  "Use this section for lower-priority supporting details that may still be useful.",
  "Do not repeat the At a Glance section.",
  "Do not write long narrative paragraphs.",
  "Group notes by topic when possible.",
  "Include speaker names only when clearly supported.",
  "",
  "Meeting-type handling:",
  "For Weekly Sales meetings, emphasize:",
  "- Customer blockers",
  "- Revenue movement",
  "- Collections and payment follow-up",
  "- Quote activity",
  "- New opportunities",
  "- Customer demand changes",
  "- Staffing and capacity risks",
  "- Job setup requirements",
  "- Forecast, sales, CRM, and reporting cleanup",
  "- Decisions, risks, action items, and open questions",
  "",
  "For Weekly SPQRC meetings, emphasize:",
  "- Safety",
  "- People",
  "- Quality",
  "- Responsiveness / delivery",
  "- Cost",
  "- Plant updates",
  "- Decisions",
  "- Risks",
  "- Actions",
  "",
  "For Individual Plant Meetings, emphasize:",
  "- Plant operations",
  "- Schedule",
  "- Safety",
  "- Quality",
  "- Staffing",
  "- Constraints",
  "- Equipment",
  "- Materials",
  "- Customer needs",
  "- Actions",
  "",
  "For General meetings, use a concise business recap structure:",
  "- At a Glance",
  "- Key Discussion Points",
  "- Decisions",
  "- Actions",
  "- Risks",
  "- Open Questions",
  "- Reference Notes",
  "",
  "Quality check before returning JSON:",
  "- The most important business items appear first.",
  "- The recap does not start with generic meeting context unless no substantive content exists.",
  "- Action items are deduplicated.",
  "- Decisions are separated from action items.",
  "- Risks are separated from open questions.",
  "- The recap does not repeat sections from multiple transcript chunks.",
  "- Unclear information is marked clearly instead of guessed.",
  "- No unsupported owner, deadline, metric, customer, plant, or decision is invented."
].join("\n");

const legacyDefaultRecapPrompts = new Set([
  [
    "You generate meeting recaps from transcripts. Return strict JSON only.",
    "Do not invent facts, owners, due dates, decisions, risks, or follow-ups.",
    "If no decision or action item is present, return an empty array for that field."
  ].join("\n"),
  [
    "You generate meeting notes from transcripts. Return strict JSON only.",
    "Do not invent facts, owners, due dates, decisions, risks, or follow-ups.",
    "If no decision or action item is present, return an empty array for that field."
  ].join("\n"),
  previousDefaultRecapPrompt,
  currentDefaultRecapPrompt
]);

export const defaultRecapSections = recapSectionKeys.map((key) => ({
  key,
  label: recapSectionLabels[key],
  enabled: true
}));

export const appSettingsSchema = z.object({
  companyName: z.string().trim().min(1),
  primaryDomain: domainSchema,
  timeZone: timeZoneSchema.optional().default(defaultTimeZone),
  allowedDomains: z.array(domainSchema).min(1),
  recorderEmail: z.string().trim().email().transform((value) => value.toLowerCase()),
  recorderAliasEmails: z
    .array(z.string().trim().email().transform((value) => value.toLowerCase()))
    .optional()
    .default([]),
  attendee: z.object({
    baseUrl: z.string().trim().url(),
    apiKeyConfigured: z.boolean(),
    webhookSecretConfigured: z.boolean(),
    botName: z.string().trim().min(1),
    createBotMinutesBeforeStart: z.number().int().min(0).max(180),
    maxWaitingRoomMinutes: z.number().int().min(1).max(240),
    deleteAttendeeDataAfterTranscriptFetch: z.boolean(),
    botImage: botImageSchema.optional(),
    botPayloadOverridesJson: z.string().optional()
  }),
  ai: z.object({
    provider: z.enum(["openai-compatible", "workers-ai"]),
    baseUrl: z.string().trim().url().optional().or(z.literal("")),
    model: z.string().trim().min(1),
    apiKeyConfigured: z.boolean()
  }),
  email: z.object({
    provider: z.enum(["cloudflare-email-service", "smtp", "mock"]),
    senderEmail: z.string().trim().email().transform((value) => value.toLowerCase()),
    testRecipient: z.string().trim().email().optional().or(z.literal("")),
    sendMeetingRecapsAutomatically: z.boolean().optional().default(false)
  }),
  policy: z.object({
    sendToAllowedDomainsOnly: z.literal(true),
    allowSubdomains: z.boolean(),
    sendToExternalAttendees: z.literal(false),
    rejectExternalOrganizers: z.boolean(),
    requireAtLeastOneEligibleRecipient: z.boolean()
  }),
  retention: z.object({
    rawInviteDays: z.number().int().min(1).max(3650),
    transcriptDays: z.number().int().min(1).max(3650),
    summaryDays: z.number().int().min(1).max(3650),
    auditLogDays: z.number().int().min(1).max(3650),
    attendeeDeleteDataAfterDays: z.number().int().min(0).max(3650)
  }),
  recap: z
    .object({
      transcriptionModel: z.string().trim().min(1),
      language: z.string().trim().max(12).optional().or(z.literal("")),
      prompt: z.string().trim().min(20).max(24000),
      subjectPrefix: z.string().trim().min(1).max(80),
      introText: z.string().trim().max(1000).optional().or(z.literal("")),
      classificationEnabled: z.boolean().optional().default(defaultRecapConfig.classificationEnabled),
      defaultTemplate: z.enum(defaultRecapTemplateKeys).optional().default(defaultRecapConfig.defaultTemplate),
      enabledTemplates: z.array(z.enum(recapTemplateKeys)).optional().default(defaultRecapConfig.enabledTemplates),
      shortMeetingBriefRecapEnabled: z.boolean().optional().default(defaultRecapConfig.shortMeetingBriefRecapEnabled),
      shortMeetingDurationThresholdMinutes: z.number().int().min(1).max(30).optional().default(defaultRecapConfig.shortMeetingDurationThresholdMinutes),
      transcriptDownloadExpirationHours: z.number().int().min(1).max(24).optional().default(defaultRecapConfig.transcriptDownloadExpirationHours),
      sections: z.array(recapSectionSchema).min(1)
    })
    .optional()
    .default({
      transcriptionModel: defaultRecapConfig.transcriptionModel,
      language: defaultRecapConfig.language,
      prompt: defaultRecapPrompt,
      subjectPrefix: defaultRecapConfig.subjectPrefix,
      introText: defaultRecapConfig.introText,
      classificationEnabled: defaultRecapConfig.classificationEnabled,
      defaultTemplate: defaultRecapConfig.defaultTemplate,
      enabledTemplates: defaultRecapConfig.enabledTemplates,
      shortMeetingBriefRecapEnabled: defaultRecapConfig.shortMeetingBriefRecapEnabled,
      shortMeetingDurationThresholdMinutes: defaultRecapConfig.shortMeetingDurationThresholdMinutes,
      transcriptDownloadExpirationHours: defaultRecapConfig.transcriptDownloadExpirationHours,
      sections: defaultRecapSections
    })
});

export type AppSettings = z.infer<typeof appSettingsSchema>;

export const defaultSettings: AppSettings = {
  companyName: "Minutesbot Demo",
  primaryDomain: "wgs.bot",
  timeZone: defaultTimeZone,
  allowedDomains: ["wgs.bot"],
  recorderEmail: "notetaker@wgs.bot",
  recorderAliasEmails: [],
  attendee: {
    baseUrl: "https://app.attendee.dev",
    apiKeyConfigured: false,
    webhookSecretConfigured: false,
    botName: "minutesbot",
    createBotMinutesBeforeStart: 0,
    maxWaitingRoomMinutes: 15,
    deleteAttendeeDataAfterTranscriptFetch: false
  },
  ai: {
    provider: "openai-compatible",
    baseUrl: "https://api.openai.com/v1",
    model: "gpt-4.1-mini",
    apiKeyConfigured: false
  },
  email: {
    provider: "mock",
    senderEmail: "notetaker@wgs.bot",
    testRecipient: defaultSampleRecapRecipient,
    sendMeetingRecapsAutomatically: false
  },
  policy: {
    sendToAllowedDomainsOnly: true,
    allowSubdomains: false,
    sendToExternalAttendees: false,
    rejectExternalOrganizers: true,
    requireAtLeastOneEligibleRecipient: true
  },
  retention: {
    rawInviteDays: 30,
    transcriptDays: 30,
    summaryDays: 365,
    auditLogDays: 365,
    attendeeDeleteDataAfterDays: 0
  },
  recap: {
    transcriptionModel: defaultRecapConfig.transcriptionModel,
    language: defaultRecapConfig.language,
    prompt: defaultRecapPrompt,
    subjectPrefix: defaultRecapConfig.subjectPrefix,
    introText: defaultRecapConfig.introText,
    classificationEnabled: defaultRecapConfig.classificationEnabled,
    defaultTemplate: defaultRecapConfig.defaultTemplate,
    enabledTemplates: defaultRecapConfig.enabledTemplates,
    shortMeetingBriefRecapEnabled: defaultRecapConfig.shortMeetingBriefRecapEnabled,
    shortMeetingDurationThresholdMinutes: defaultRecapConfig.shortMeetingDurationThresholdMinutes,
    transcriptDownloadExpirationHours: defaultRecapConfig.transcriptDownloadExpirationHours,
    sections: defaultRecapSections
  }
};

export function parseSettings(input: unknown): AppSettings {
  const parsed = appSettingsSchema.parse(input);
  return {
    ...parsed,
    allowedDomains: Array.from(new Set(parsed.allowedDomains.map((domain) => domain.toLowerCase()))),
    primaryDomain: parsed.primaryDomain.toLowerCase(),
    timeZone: parsed.timeZone,
    recorderEmail: parsed.recorderEmail.toLowerCase(),
    recorderAliasEmails: normalizeRecorderAliasEmails(parsed.recorderEmail, parsed.recorderAliasEmails),
    email: {
      ...parsed.email,
      senderEmail: parsed.email.senderEmail.toLowerCase(),
      testRecipient: parsed.email.testRecipient ? parsed.email.testRecipient.toLowerCase() : undefined,
      sendMeetingRecapsAutomatically: parsed.email.sendMeetingRecapsAutomatically
    },
    recap: normalizeRecapSettings(parsed.recap)
  };
}

function normalizeRecorderAliasEmails(recorderEmail: string, aliases: string[]): string[] {
  const primary = recorderEmail.toLowerCase();
  return Array.from(new Set(aliases.map((email) => email.toLowerCase()))).filter((email) => email !== primary);
}

function isValidTimeZone(value: string): boolean {
  try {
    new Intl.DateTimeFormat("en", { timeZone: value }).format(new Date());
    return true;
  } catch {
    return false;
  }
}

function normalizeRecapSettings(recap: AppSettings["recap"]): AppSettings["recap"] {
  const provided = new Map(recap.sections.map((section) => [section.key, section]));
  const ordered = recap.sections.map((section) => section.key);
  for (const key of recapSectionKeys) {
    if (!ordered.includes(key)) ordered.push(key);
  }
  return {
    ...recap,
    language: recap.language ?? "",
    introText: recap.introText ?? "",
    classificationEnabled: false,
    defaultTemplate: defaultRecapConfig.defaultTemplate,
    enabledTemplates: normalizeEnabledTemplates(recap.enabledTemplates),
    shortMeetingBriefRecapEnabled: recap.shortMeetingBriefRecapEnabled ?? defaultRecapConfig.shortMeetingBriefRecapEnabled,
    shortMeetingDurationThresholdMinutes: recap.shortMeetingDurationThresholdMinutes ?? defaultRecapConfig.shortMeetingDurationThresholdMinutes,
    transcriptDownloadExpirationHours: recap.transcriptDownloadExpirationHours ?? defaultRecapConfig.transcriptDownloadExpirationHours,
    prompt: legacyDefaultRecapPrompts.has(recap.prompt) ? defaultRecapPrompt : recap.prompt,
    sections: ordered.map((key) => {
      const section = provided.get(key);
      return section ?? { key, label: recapSectionLabels[key], enabled: true };
    })
  };
}

function normalizeEnabledTemplates(_templates: AppSettings["recap"]["enabledTemplates"] | undefined): AppSettings["recap"]["enabledTemplates"] {
  return defaultRecapConfig.enabledTemplates;
}

export function resolveAttendeeBaseUrl(settingsBaseUrl: string, envBaseUrl?: string): string {
  if (legacySelfHostedAttendeeBaseUrls.has(settingsBaseUrl.replace(/\/+$/, "")) && envBaseUrl) return envBaseUrl;
  return settingsBaseUrl || envBaseUrl || defaultSettings.attendee.baseUrl;
}
