import { Hono } from "hono";
import { getSettings } from "@minutesbot/db";
import { createEmailProvider, createPolicyEnforcedProvider, formatEmailAddress } from "@minutesbot/email-sender";
import { renderRecapEmail } from "@minutesbot/email-renderer";
import { parseIncomingInvite } from "@minutesbot/invite-parser";
import { BotClientError } from "@minutesbot/bot-client";
import { AppError, readJsonWithLimit, readTextWithLimit } from "@minutesbot/shared";
import { createRuntimeClient } from "../../../workflow-worker/src/botRuntime";
import type { Env } from "../env";

const MAX_TEST_BODY_BYTES = 1024 * 1024;

const sampleRecap = {
  overview: "This is a connectivity test recap generated by the admin test action.",
  decisions: ["Confirmed outbound email delivery works"],
  actionItems: [{ task: "Nothing to do — this is a test", owner: "minutesbot" }],
  risks: [],
  openQuestions: [],
  importantDates: [],
  followUps: []
};

export const testActionsRoute = new Hono<{ Bindings: Env }>()
  .get("/status", async (c) => {
    return c.json({
      environment: c.env.ENVIRONMENT ?? "unset",
      apiBaseUrl: c.env.API_BASE_URL,
      appBaseUrl: c.env.APP_BASE_URL,
      botRuntime: { baseUrl: c.env.BOT_API_BASE_URL, viaServiceBinding: Boolean(c.env.BOT_RUNTIME) }
    });
  })
  .post("/test-d1", async (c) => {
    await c.env.DB.prepare("SELECT 1").first();
    return c.json({ ok: true });
  })
  .post("/test-r2", async (c) => {
    const key = `diagnostics/system/r2-test-${crypto.randomUUID()}.txt`;
    await c.env.ARTIFACTS.put(key, "ok");
    const object = await c.env.ARTIFACTS.get(key);
    await c.env.ARTIFACTS.delete(key);
    if (!object) throw new AppError("R2_TEST_FAILED", "R2 round-trip failed: object not found after put.", 500);
    return c.json({ ok: true });
  })
  .post("/test-bot", async (c) => {
    const client = createRuntimeClient(c.env);
    try {
      const health = await client.checkHealth();
      const ready = await client.checkReady();
      return c.json({ ok: health.ok && ready.ready, health, ready });
    } catch (error) {
      if (error instanceof BotClientError) throw new AppError(error.code, error.message, 502);
      throw error;
    }
  })
  .post("/test-ai", async (c) => {
    if (!c.env.AI_API_KEY) throw new AppError("AI_NOT_CONFIGURED", "Set the AI_API_KEY secret first.", 503);
    const settings = await getSettings(c.env.DB);
    const baseUrl = (settings.recap.baseUrl || "https://api.openai.com/v1").replace(/\/+$/, "");
    const response = await fetch(`${baseUrl}/chat/completions`, {
      method: "POST",
      headers: { "content-type": "application/json", authorization: `Bearer ${c.env.AI_API_KEY}` },
      body: JSON.stringify({
        model: settings.recap.model,
        messages: [{ role: "user", content: "Reply with the single word: ok" }],
        max_tokens: 5
      }),
      signal: AbortSignal.timeout(30_000)
    });
    if (!response.ok) {
      throw new AppError("AI_TEST_FAILED", `AI provider responded with ${response.status}.`, 502);
    }
    return c.json({ ok: true, model: settings.recap.model });
  })
  .post("/test-email", async (c) => {
    const settings = await getSettings(c.env.DB);
    const recipient = settings.email.testRecipient;
    if (!recipient) throw new AppError("NO_TEST_RECIPIENT", "Configure a test recipient in settings first.", 400);
    const provider = createPolicyEnforcedProvider(
      createEmailProvider({ provider: settings.email.provider, sendEmailBinding: c.env.SEND_EMAIL }),
      { allowedDomains: settings.allowedDomains, allowSubdomains: settings.policy.allowSubdomains }
    );
    const rendered = renderRecapEmail({
      subject: "minutesbot test email",
      recap: sampleRecap,
      subjectPrefix: settings.recap.subjectPrefix,
      timeZone: settings.timeZone
    });
    const result = await provider.send({
      from: formatEmailAddress(settings.email.senderName, settings.email.senderEmail),
      to: recipient,
      subject: rendered.subject,
      text: rendered.text,
      html: rendered.html
    });
    if (result.status !== "sent") throw new AppError("EMAIL_TEST_FAILED", result.failureReason ?? "Send failed.", 502);
    return c.json({ ok: true, providerMessageId: result.providerMessageId ?? null });
  })
  .post("/parse-sample-invite", async (c) => {
    const raw = await readTextWithLimit(c.req.raw, MAX_TEST_BODY_BYTES, "SAMPLE_INVITE_TOO_LARGE");
    const parsed = parseIncomingInvite(raw);
    return c.json({
      ok: true,
      parsed: {
        kind: parsed.kind,
        calendarUid: parsed.calendarUid,
        subject: parsed.subject,
        teamsJoinUrl: parsed.teamsJoinUrl,
        startTime: parsed.startTime,
        endTime: parsed.endTime,
        sequence: parsed.sequence ?? null,
        rrule: parsed.rrule ?? null,
        recurrenceId: parsed.recurrenceId?.utc ?? null,
        events: parsed.events.length,
        attendees: parsed.attendees.map((attendee) => attendee.email)
      }
    });
  })
  .post("/run-maintenance", async (c) => {
    // Manual trigger for the daily jobs — useful right after setup.
    const { createDailyMaintenanceJobs } = await import("../../../workflow-worker/src/cron");
    await createDailyMaintenanceJobs(c.env);
    return c.json({ ok: true });
  })
  .post("/echo-settings", async (c) => {
    // Round-trips a settings payload through validation without saving.
    const body = await readJsonWithLimit(c.req.raw, MAX_TEST_BODY_BYTES);
    const { parseSettings } = await import("@minutesbot/shared");
    return c.json({ ok: true, settings: parseSettings(body) });
  });
